### ISSUE TITLE
Content warnings display on Twitter

### ISSUE THREAD

**Issue by skiant** [renatolond/mastodon-twitter-poster#1]
Just a tiny thing, but when I post behind a CW (ie: https://witches.town/@Skiant/4201602) it would be cool if the Twitter post had `[CW xxx]` to start with, instead of posting the message without warning. (https://twitter.com/skiant/status/896692994446962689).

Maybe if you'd like to go overboard, the entire post on Twitter could be just the CW and the link, so that we rely on Mastodon's better handling of CWs.

**Comment by renatolond** [comment]
I went for posting only `CW: text` and the link for the time being. It's easier to rely on Mastodon's treating of CW instead :)
