### ISSUE TITLE
Boosts from Pleroma are missing content/links

### ISSUE THREAD

**Issue by anaskaejdar** [renatolond/mastodon-twitter-poster#103]
If I boost something from pleroma, the crossposter boosts it on twitter too, except both the content of the message and the link to it are missing.  Instead, it just says "Boosted: " with nothing following the colon.

![screenshot](https://user-images.githubusercontent.com/32847759/40861726-f53f3886-659e-11e8-9ea6-a409d007bd35.png)
That's what happened when I boosted this: https://mastodon.social/@rotatingskull/100131426584876021

**Comment by renatolond** [comment]
Hey!
I haven't tested the crossposter at all with pleroma, I'll try to take a look, but I don't use it and don't know how compatible the API is supposed to be. In theory, if the pleroma API is compatible enough with the Mastodon one, it should just work, but it seems it's not the case.

**Comment by renatolond** [comment]
Indeed, it's an issue in the Mastodon-like API from Pleroma. I created an issue at Pleroma's gitlab: https://git.pleroma.social/pleroma/pleroma/issues/231

**Comment by barudaret** [comment]
Thanks for looking into this dude, you're awesome.  God bless you man. 💪

**Comment by renatolond** [comment]
This was fixed over in pleroma in https://git.pleroma.social/pleroma/pleroma/merge_requests/246/diffs, should be fixed as soon as it starts to be deployed in the next few days :)
