### ISSUE TITLE
twitter -> fediverse - Replace name in Rt by screen_name

### ISSUE THREAD

**Issue by ghost** [renatolond/mastodon-twitter-poster#105]
Is it possible to replace the name that's shown when you RT a tweet by the screen name of the user ?
For example replacing "RT @Qofficiel@twitter.com: " by "RT Quotidien: "

**Comment by renatolond** [comment]
It is possible, but I don't know if it makes a lot of sense, a quick look on my timeline and I can't see screen names like:
`🌿 1,6km  🌿 #AvecMoiLe26Mai`
`HardDiscountResearcher`
`Sex Therapist`
between others, all of this legitimate accounts.

Screen name is very often used for moods and except for official twitter account, change often.
