### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by batarian71** [renatolond/mastodon-twitter-poster#108]
Hello. I am a graphic designer. I want to volunteer support for open source projects. If you want, I can design a logo for you. What do you say?

**Comment by renatolond** [comment]
Hey, @batarian71 ! The service already uses a logo at https://masto.donte.com.br/@crossposter, if you want to improve on that one, please feel free :)

**Comment by batarian71** [comment]
I designed a simpler and more characteristic logo. I hope you like it. 

![asdadad](https://user-images.githubusercontent.com/36008612/41520630-5b2d5476-72d7-11e8-92e7-ca020f397e2b.jpg)

**Comment by renatolond** [comment]
Hey @batarian71, I really like the idea, but I think the M does not remind me of mastodon much, maybe a more similar font to the mastodon one or a small elephant-like drawing?

**Comment by batarian71** [comment]
I will change the font. Then I will send a pr.

**Comment by batarian71** [comment]
I sent pr.
