### ISSUE TITLE
Auto-CW tweets that contain a word or hashtag

### ISSUE THREAD

**Issue by Skirmisher** [renatolond/mastodon-twitter-poster#109]
I've introduced a friend of mine to the crossposter, and she's gotten a lot of use out of it, since she uses Twitter much more that Mastodon but still wants to keep up with people on the latter platform. However, given that E3 is going on, she's been applying a blanket content warning in the crossposter settings to allow Mastodonians to filter out her E3 livetweeting, and occasionally editing it when she stops/starts talking about it.

She would like to use the auto-CW behavior of the crossposter, but finds the "CW: warning" syntax to be unfitting for something like this. She would prefer the crossposter automatically CW her tweets that contain the hashtag #E3. That way, it's grouped appropriately on both Twitter and Mastodon (e.g. for searching or muting), it appears appropriate on Twitter, and Mastodon users have control over seeing it like they're used to.

This sort of function could also apply to words whose presence often indicate discussion of the issue in question (e.g. racism or transphobia), and also allows one to use these common warnings in more inline formats. I'm not personally familiar with how said formats are used, so I can't justify filing another issue to amend the CW detector on my own, but I've seen things like "warning)" or "warning//" at the beginning of tweets. For those who use these on Twitter, I'd appreciate your comments!

Regarding the actual issue topic, the simplest feature implementation would be a list of words in the crossposter settings that add a CW with the word Mastodon-side. Multiple words in the same tweet would end up as a comma-separated list in the Masto CW. (The words themselves would not be removed from the resulting toot, due to the imprecise nature of the feature.) A more complex setup would see words mapped to CWs (e.g. "transphobic" would turn into a "transphobia" CW), but I'm not sure how much use that would get. I think the simple form is most applicable to livetweeted events that come with a common name and/or hashtag, and would benefit the most from a quicker, simpler implementation.

**Comment by renatolond** [comment]
I think this is kinda related to #85.

If I understand well, the idea would be something like this, in the crossposter I would have a new field like:

```
If a tweet contain one of these words, use them as cw: alice bob zordon #megazord
```

Then, if I tweet:

```
OMG, you won't believe it, but when I was watching power rangers yesterday, megazord appeared just at the last minute! Also, was zordon always that annoying?
```

The resulting toot would be:

```
CW: #megazord, zordon
OMG, you won't believe it, but when I was watching power rangers yesterday, #megazord appeared just at the last minute! Also, was zordon always that annoying?
```

Is that it?

**Comment by Skirmisher** [comment]
That's exactly it! :)
