### ISSUE TITLE
Prepend custom text to crossposted tweets

### ISSUE THREAD

**Issue by kit-ty-kate** [renatolond/mastodon-twitter-poster#112]
One of `Twitter -> Mastodon` features is to add a content warning to all tweets. This is a cool feature, however if we just want to indicate that this post comes from Twitter for example, there is no way to do it without using the CW feature which becomes a bit annoying for your followers.

Is it possible to get a feature to allow to prepend some text to the crossposted tweets ?

**Comment by renatolond** [comment]
Hi, @kit-ty-kate! When you RT stuff from Twitter you already get the `RT @user@twitter` prepended, you want to prepend text to your own tweets before crossposting them?

**Comment by kit-ty-kate** [comment]
> you want to prepend text to your own tweets before crossposting them?

yes, if that's possible :)

**Comment by renatolond** [comment]
How would it work regarding the types of tweet?
Currently we consider a tweet either a regular tweet (i.e one that you authored), a retweet or a quote. All of them would have the "Coming from twitter: " (or other configured text) ahead of them?

**Comment by kit-ty-kate** [comment]
mmh I'd say maybe same as the CW feature
```
Any text added to this box will be used as content warning for every toot crossposted from twitter (except for tweets in which specific CWs are detected)
```
I guess otherwise it's pretty obvious it comes from twitter because the toot would have either an url pointing to twitter or a twitter handle

**Comment by tonnerre** [comment]
IMHO it would be nice to be able to add a hashtag to any content cross-posted from Twitter so people can filter that easily.
