### ISSUE TITLE
Ability to toggle privacy options when replying to ourselves in Twitter.

### ISSUE THREAD

**Issue by nursemchurt** [renatolond/mastodon-twitter-poster#116]
As a courtesy to people's timelines on Mastodon, I've taken to setting replies to myself as unlisted when making a long threaded series of posts. Unfortunately, I'm not able to do the same with my crossposts from Twitter to Mastodon.

For myself, it hasn't been much of an issue, however it does discourage me to have the crossposter on when I would like to livetweet or any kind of self-reply chain that would be longer than a few.

**Comment by HunterZ** [comment]
I would also very much like to see this. I polled the Mastodon community, and the preferred threading approach seems to be having the first toot in a long thread being public but the replies unlisted so as not to "spam" the timelines of non-followers.

Specifically, I'm looking for an option to make original tweets->toots be public, but self reply tweets->toots be unlisted.

**Comment by renatolond** [comment]
I haven't had the time to work on new features for the crossposter lately. I'm open to contributions, but I probably won't have the time to check this myself.
