### ISSUE TITLE
Add an option for a time interval

### ISSUE THREAD

**Issue by joenepraat** [renatolond/mastodon-twitter-poster#123]
Some people want to crosspost only every X minutes. Example: John wants to forward his tweets only every 30 minutes (1 per 30 min.), so his Mastodon buddies won't start complaining about flooding. 

An option for users where they can configure a minimum time interval would solve this. Tweets that are not yet allowed to crosspost are than queued for delivery. If there are no tweets in this queue and the last crosspost was longer ago than the configured time interval, the tweet is crossposted immediately.

**Comment by renatolond** [comment]
The idea is that one individual post will get crossposted every 30 min or that every 30 min every available post will be crossposted?

As in, if I did three posts:

[00:00:00] "Hey!"
[00:00:20] "I like this place"
[00:00:40] "How are you people?"
[00:01:20] "Hm, actually, I don't like it"

This gets crossposted as:

[00:00:30] "Hey!"
[00:30:00] "I like this place"
[01:00:00] "How are you people?"
[01:30:00] "Hm, actually I don't like it"

Or 
[00:01:00] "Hey!"
[00:01:00] "I like this place"
[00:01:00] "How are you people?"
[00:31:00] "Hm, actually, I don't like it"

**Comment by jeroenpraat** [comment]
The first one.

[00:00:30] "Hey!"
[00:30:00] "I like this place"
[01:00:00] "How are you people?"
[01:30:00] "Hm, actually I don't like it"

Absolutely not the second, cause this is to avoid flooding peoples Mastodon timelines. A good interval default (if enabled) would be 10 minutes I think.

**Comment by renatolond** [comment]
This would generate a backlog of messages which would eventually lead to statuses being lost (on both sides there's a default number messages which are returned when I ask for statuses since the last status).

I also don't understand how this prevents flooding, if the user is posting directly on Mastodon instead using the web interface, isn't the effect the same?

**Comment by jeroenpraat** [comment]
The backlog can be avoided to have a maximum interval of 60 minutes.

About flooding: on Twitter there is much more traffic than on Mastodon. Also Twitter has no local timelines that on smaller instances can flood with a lot of crossposters.

**Comment by renatolond** [comment]
When you say max interval, you mean that after that we drop the message or that all messages get posted at once?

**Comment by jeroenpraat** [comment]
No, that this is the maximum interval setting.

**Comment by renatolond** [comment]
Ah, okay, but I don't think that helps with old messages being dropped, if you're using twitter constantly and you have an interval set, eventually you're going to get messages dropped because they fall behind the window of status that the API gives me by default

**Comment by jeroenpraat** [comment]
Yes, well maybe a message with a warning would be enough and the max. interval of 60 min. even lower (e.g. 45 min).

But it is just an idea after I saw a crossposter flooding my local timeline in a short time period.

**Comment by renatolond** [comment]
Hm, I feel like this could be part of #124, not as a user configuration, but as an instance-wide configuration for the crossposter. It would then appear as a warning to the user.

**Comment by jeroenpraat** [comment]
Maybe, I can't judge that.
