### ISSUE TITLE
Mastodon to Twitter posting question,

### ISSUE THREAD

**Issue by LWFlouisa** [renatolond/mastodon-twitter-poster#125]
Is there any recent news on the current status of being able to post to Twitter from Mastodon? For me it was working sporadically, but seems to be dead after the announcement.

**Comment by renatolond** [comment]
Hi!
Mastodon to Twitter is still offline if you're using https://crossposter.masto.donte.com.br, Twitter still hasn't answered our last emails. I'm trying to post news as they come in this thread: https://masto.donte.com.br/@crossposter/100519692225352736
If you need, there are other services like https://moa.party, or the browser extension https://gitlab.com/pmorinerie/birdsite . If you decide to change do not forget to disable the crossposter to avoid double posting. 
Sorry for the inconvenient!
