### ISSUE TITLE
Add an option to ignore Tweets that have too many @-mentions

### ISSUE THREAD

**Issue by pietsch** [renatolond/mastodon-twitter-poster#127]
A friendly Mastodon instance operator asked me not to crosspost tweets with a lot of @-mentions.
Would you please add an option that takes a non-negative integer as input and makes the bridge ignore tweets with more @-mentions than that?

Alternatively, tweets with more @-mentions than the specified threshold could be crossposted with visibility “unlisted”.

**Comment by pietsch** [comment]
By all means, let's try the simple solution first. It might do the job.

I think that this issue is not related to #106 because my use case is non-replies.

**Comment by p0sty** [comment]
I think We've found a solution over at https://github.com/renatolond/mastodon-twitter-poster/issues/606 !

just add "@" to the ignore list, it works! at least for me.
