### ISSUE TITLE
Do posts with only media in them still need a 🖼 emoji in them?

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#128]
Mastodon removed the `.` from posts that contain only images in [2.4.2 in June 2018](https://github.com/tootsuite/mastodon/releases/tag/v2.4.2). I don't know if crossposter updates line up but I thought I would draw this to your attention, just in case it's helpful!

**Comment by renatolond** [comment]
Thanks for the reminder, I had forgot about this, but I think I'll wait for Switter to update beyond 2.4.2, right now they're in 2.3.3 and there's a lot of people over there using the crossposter, which would probably break if I remove it.
I need to find a good way to check the quantity of instances that updated beyond that, neither fediverse.network nor instances.social have something like that and mnn.social seems to be out-of-date :disappointed:

**Comment by Cassolotl** [comment]
Ahh yeah, fair enough! :)

**Comment by renatolond** [comment]
I checked and this affected less instances that I originally thought, so it's solved!
Thanks!

**Comment by Cassolotl** [comment]
Oh cool, alright then! :)
