### ISSUE TITLE
Auto-CW fails if a tweet only contains media

### ISSUE THREAD

**Issue by remhume** [renatolond/mastodon-twitter-poster#130]
The problem here is that it is assumed that there always is a newline after the CN, but if you only write the CN and add media there is no newline.

Because the newline thing seems deliberate to prevent false detections (?) i'd suggest testing for either a newline or an end-of-string, depending on the tweet having media attached or not.

Example: https://cybre.space/@remmy/100803665942639948
<img width="429" alt="screenshot 2018-09-28 at 15 52 45" src="https://user-images.githubusercontent.com/3317423/46212584-a1807200-c336-11e8-8991-bb4462565558.png">

**Comment by renatolond** [comment]
Hm, I overlooked that case, indeed :)
I'll check it out later today, thanks for reporting!
