### ISSUE TITLE
Blocklist didn't work for Twitter -> Mastodon, with unicode string.

### ISSUE THREAD

**Issue by remhume** [renatolond/mastodon-twitter-poster#136]
Hey, i just tried the new blocklist and tried to have a cool unicode sign for stopping crossposts: `<≠>`

That was the only content in the wordlist textarea, the setting was set to "do not crosspost" (blocklist).

However after tweeting something with that in it (`test <≠>`) it got crossposted just fine.

This seems like a bug to me. Is there an issue with the used characters? Does the regex maybe not see that as one "word" eventhough it is an exact match?

**Comment by remhume** [comment]
Sorry, prematurely submitted, one moment.

**Comment by remhume** [comment]
I just tried using a "normal" word (`nocross`) and it seems to work fine, so the characters seem to indeed be the culprit here

**Comment by renatolond** [comment]
Hmm, it seems it should work, I created a user with only that word in the twitter word list, and it seems that this would be the regex result:

http://rubular.com/r/G2IeOGLzZk

However, I didn't test creating it through the web interface, I'll test that later

**Comment by renatolond** [comment]
Hey! Got some time to look into this, the problem is not the unicode character, but twitter escapes `<` and `>` to `&lt;` and `&gt;`. I'm going to look into a fix, thanks for reporting :)
