### ISSUE TITLE
Option for crossposting CW without links

### ISSUE THREAD

**Issue by ardydo** [renatolond/mastodon-twitter-poster#137]
While I understand that it's intended to bring people to mastodon, the end result is just way less people interacting with the posts if it's just a warning with a link.

Currently I'm finding myself just posting more and more on twitter so I can use the manual CW'ing and have my posts show up in both and I don't alienate my twitter followers from my content and neither subject my mastodon followers to CW'ed content. Making a toggle would make it so people can choose to keep using links or changing it.

**Comment by ardydo** [comment]
I was thinking just:

> 
> CW: HERE BE MONSTERS
> 
> Bigfoot
> 

So it's clearer it's a warning (what are the CW conventions in twitter?) but I don't really know what would be better.

Linking back is not the main issue, I guess because of the wording it may seem like it, the main issue is having the content behind the link, usually, it's all the content. For a big toot for example, I don't think it would be an issue to have the link to the rest of the toot

**Comment by renatolond** [comment]
I never found one convention, I see sometimes people using it as `[content]` sometimes as `[tw: content]` or similar.

I think `[cw: content]` or `cw: content` should be fine. :)

**Comment by jmacmahon** [comment]
I'm considering implementing this -- how about `[cn: content]`?

Argument in favour: I think 'CN' is a more appropriate term for what CWs are widely used for on Mastodon.

Argument against: The Mastodon terminology is explicitly CW rather than CN, and we should not break that convention.

**Comment by renatolond** [comment]
Hey!
I think as long as it's easy-ish to change in the code, it should be fine, since we can adapt as the feature goes live :)

**Comment by jmacmahon** [comment]
I'm actually struggling to get a dev environment set up tbh. It would be good to have a docker-compose or something so that I don't have to worry about missing libraries (there were 3 that I had to install that were not in the documentation) and configuring postgres correctly (I couldn't work out how to specify the right user) etc.

**Comment by singingwolfboy** [comment]
It would also be nice to have an option to simply ignore the content warning when crossposting from Mastodon to Twitter. That is, if my Mastodon post looks like this:

> CW: this is the content warning
> this is the content

Then the corresponding Twitter post could just look like this:

> this is the content

I am not suggesting that this should be the default! But it would be nice if there was an option to make that possible.

**Comment by renatolond** [comment]
Fixed on #476 :)
