### ISSUE TITLE
Twitter username isn't converted when it's in brackets

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#145]
[Original post](https://twitter.com/cassolotl/status/1066259640789405697):

![screen shot 2018-11-24 at 10 38 26](https://user-images.githubusercontent.com/6607512/48967219-1ab5e180-efd5-11e8-80a6-55743914e052.png)

[Crosspost](https://dev.glitch.social/@cassolotl/101125399197631681):

![screen shot 2018-11-24 at 10 38 53](https://user-images.githubusercontent.com/6607512/48967222-2903fd80-efd5-11e8-9318-89aee49d4125.png)

Usually it gets expanded into something like `@username@twitter.com`.

It might not be the brackets but that's my best guess!

**Comment by renatolond** [comment]
Most likely the brackets :smile: I'll take a look, thanks!

**Comment by Cassolotl** [comment]
Woo! Thank you so much for your work on this. :)
