### ISSUE TITLE
Compose one's own crosspost template

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#146]
This is ambitious and may not be possible, but I thought I'd propose it just in case you think it's awesome and you want to make it. :D 

So let's say I tweet this:

![screen shot 2018-11-24 at 10 43 21](https://user-images.githubusercontent.com/6607512/48967273-cbbc7c00-efd5-11e8-9499-40180c333c58.png)

For quote options I have this setting selected: "Post quotes on Mastodon as old-style RTs with links (I like this idea RT @renatolonddev@twitter.com: Hello, world! https://twitter.com/renatolonddev/status/904738384861700096)"

On Mastodon it comes out like this:

![screen shot 2018-11-24 at 10 44 25](https://user-images.githubusercontent.com/6607512/48967282-f3134900-efd5-11e8-8dc3-dff5b583356d.png)

And then, because that whole zone around the username and the start of the quoted tweet and the end of the commentary sort of blurs together, I usually delete-and-redraft to add some carriage returns like so:

![screen shot 2018-11-24 at 10 45 41](https://user-images.githubusercontent.com/6607512/48967294-1d650680-efd6-11e8-9588-ccc17f95ce24.png)

Which makes it take up a little more space, but it also makes things a lot clearer. BUT I imagine that other people would prefer to keep it the way it is, without the carriage returns?

So I'm thinking it would be awesome to have a thing like I saw on IFTTT, where there's a text box and a list of codes next to it, and one could compose their quote-tweet arrangement of words. You might type into the box something like this to compose your perfect quote-tweet template:

```
[quotetweet_text]

RT: [OP_username_twitter]
[OP_tweet_twitter]

🐦🔗: [OP_URL_twitter]
```

Which would come out like:

> Wow, this is awesome!
> 
> RT: @person@twitter.com
> I'm So Meta Even This Acronym. :OOO 
> 
> 🐦🔗: https://twitter.com/person/status/111111111111111

**Comment by renatolond** [comment]
Hm, I like this idea a lot :)

Maybe as an advanced/optional configuration, but I certainly like it. I'll sleep on it a bit to think of possible issues and how to go around them, but great one :heart:

**Comment by Cassolotl** [comment]
Oooo and people could put "CW: Twitter crosspost" in the top row if they want to add a CW to all crossposts, too! :o

**Comment by renatolond** [comment]
Hm, it depends a bit, currently the detection of the CW is before I format the toot, but I could optionally add a box for CW as part of the configuration, so indeed it could be part of it :)
(Maybe even different formattings depending if own tweet, rt or quote, so that each could have it's own cw and stuff)

**Comment by Lazza** [comment]
This would be great so that we can cross-post retweets with links only, in order to preserve the data of the original poster (who might not be happy to get their content copied and pasted over to Mastodon).
