### ISSUE TITLE
Add some carriage returns into the quote-tweet crossposter for clarity

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#147]
The start of a crossposted quote-tweet can get a bit tangled and blurry because it's all put on the same line:

![screen shot 2018-11-24 at 10 44 25](https://user-images.githubusercontent.com/6607512/48967399-9f096400-efd7-11e8-828e-99b551e282c6.png)

I usually delete and repost to add some carriage returns, so I can see what's going on:

![screen shot 2018-11-24 at 10 45 41](https://user-images.githubusercontent.com/6607512/48967403-a92b6280-efd7-11e8-9686-7c7e976416ec.png)

I think this would be my ideal for most quote-tweet crossposting purposes:

> Enthusiastic commentary!
> 
> RT @username@twitter.com
> Original quote-tweeted tweet text. :O 
> 
> 🐦🔗: https://twitter.com/username/status/111111111111

I'm posting this just in case other people feel the same way as me, but I'm *assuming* that it's just me who struggles with this, so if this gets closed because I'm the only one then that is 100% okay! :) The current way *does* save space so there are pros to each way.

**Comment by renatolond** [comment]
I remember some suggestions about readability on this one already, and I guess adding the carriage returns would help with ascii-based stuff (either the stars art or stuff like the emoji tetra), I'm in for this one :)
