### ISSUE TITLE
crossposting keyword blocklist not working (regression?)

### ISSUE THREAD

**Issue by remmycat** [renatolond/mastodon-twitter-poster#148]
It seems the blocklist had a recent regression, at least currently it cross-posts all my tweets to mastodon eventhough i'm adding a character from my keyword list.

Keyword used: `⇎`
Setting is correctly set to "Do not crosspost if it contains one of the words"

In all my cases it was the very last character in the tweet, preceeded by a space, that may be of relevance?

Example Tweet: `Test ⇎`

I'm pretty sure this was working before, but i could be wrong.

**Comment by remhume** [comment]
(closed on accident)

**Comment by renatolond** [comment]
Hmm, I can't seen to reproduce this one, this is my setup:

![image](https://user-images.githubusercontent.com/173791/49020245-45986500-f190-11e8-8f3f-f14b3c243ddd.png)
![image](https://user-images.githubusercontent.com/173791/49020268-52b55400-f190-11e8-9db3-102e355677e6.png)
![image](https://user-images.githubusercontent.com/173791/49020284-5ba62580-f190-11e8-9873-89ee127f4409.png)

Can you send me more information about your setup so I can try to see if there's anything different than on my side?
