### ISSUE TITLE
Ability to link several Twitter accounts to 1 Mastodon account.

### ISSUE THREAD

**Issue by rx65m** [renatolond/mastodon-twitter-poster#152]
It will be great to be able to link several Twitter accounts to 1 Mastodon account.
Right now, I need to switch frequently from one account to another each time I want update Mastodon from any of my Twitter accounts.
Thank you in advance.

**Comment by renatolond** [comment]
Hi!
Thanks for the suggestion, but I don't think I will support connecting multiple accounts in either direction.
The crossposter is really designed in a way that supporting such setup would be a major change, and for most of the use cases, connecting accounts 1-to-1 is good, even if you have multiple accounts. (as in: some people have a closed twitter account and an open one, and they also have a similar setup in Mastodon).

Do you mind if I ask what's your use case? in which case would you need to join the content of multiple twitter accounts into your Mastodon account?

**Comment by rx65m** [comment]
Thanks a lot for your kind reply. Sorry to know that.

I monetize my Twitter accounts. I do it for a living. I own 12 accounts in Twitter and recently made a deal with a Mastodon server owner to help with huge amount of people coming to Mastodon from Tumblr and Twitter due to upcoming bans. So I'm migrating to Mastodon too, but I want to reduce my accounts from 12 to 3 to to make things easier at Mastodon. I want to post all my content from groups of 4 Twitter accounts to a 1 unified account at Mastodon.
I actually spent the last 5 months doing this with and IFTTT applet, from Twitter to Tumblr, but now is useless.

There was an applet from IFTTT able to do this from Twitter to Mastodon, but apparently is not available any more, although there are still several applets able to do this in the opposite direction: from Mastodon to Twitter.

Do you have any suggestion about it?
Thank you a lot in advance.

**Comment by renatolond** [comment]
Hmm, for 4 accounts I don't know :thinking: 
If you are only posting in one direction (i.e. Twitter -> mastodon) connecting using the crossposter and https://github.com/foozmeat/moa should work. They should not clash between each other, unless you are crossposting in both directions.

However, that will only give you 2 accounts to one. If you need more than that I think your option is to self-hosting, stuff like https://github.com/AmauryCarrade/MastodonToTwitter would allow you to create a few different bridges and use them. But you have to operate them manually. There's some other options for this setup, over here: https://github.com/tootsuite/documentation/blob/master/Using-Mastodon/Apps.md#bridges-fromto-other-platforms

I think there's a glitch one too, but only in Mastodon -> twitter direction, that one you could possibly also link multiple. (like this one https://glitch.com/~cheerful-jackal )

If I remember anything else I'll let you know!

**Comment by renatolond** [comment]
I'm closing this one for now, if you need more help let me know!
