### ISSUE TITLE
Dockerize the application

### ISSUE THREAD

**Issue by Aldarone** [renatolond/mastodon-twitter-poster#16]
Pretty much everything is in the title. I'm willing to do this but it'd be usefull if you could tell me which ports the web server and the daemons use.

**Comment by renatolond** [comment]
Hi, Alda!

The webserver takes a PORT env variable to say in which port it will run, the standard port is 3000, I think.

As for the daemon, it currently polls, so it's not using outside ports :)

**Comment by renatolond** [comment]
If you need any further clarification just let me know!

**Comment by Aldarone** [comment]
Ok so basically : 

- Web server:3000
- Worker
- Postgresql:5432

What about statsd ?

**Comment by renatolond** [comment]
Statsd is running on 8125 and takes two environment variables to connect with librato: LIBRATO_EMAIL and LIBRATO_TOKEN.
Other ENV variables that might be useful: TWITTER_CLIENT_SECRET and TWITTER_CLIENT_ID for the twitter info and DO_NOT_ALLOW_NEW_USERS to disable new users signing in.

**Comment by renatolond** [comment]
Done by #337 and #353
