### ISSUE TITLE
Add the option to use @username@twitter.activitypub.actor instead of @username@twitter.com

### ISSUE THREAD

**Issue by DavidLibeau** [renatolond/mastodon-twitter-poster#163]
https://twitter.activitypub.actor/ is providing a way to "mention" Twitter profil of Mastodon (it give an readable ActivityPub actor object).
This would be used instead of "@username@twitter.com" or "@username" when crossposting.

**Comment by renatolond** [comment]
I'll check it out! Thanks :)
