### ISSUE TITLE
Link to Mastodon post on posts Mastodin => Twitter

### ISSUE THREAD

**Issue by stevenroose** [renatolond/mastodon-twitter-poster#164]
Now it seems like I'm just using Twitter. I want it to be clear that it's just a mirror of my Mastodon identity.

Either by setting a prefix or with a link to the original post in the suffix.

**Comment by renatolond** [comment]
Hi!
I have to look into this, since in the past the crossposter got tagged by twitter as spam for mastodon links (since they all look very similar, with very small differences). In the instance of the crossposter I run, the one at masto.donte.com.br, I've disabled boosts crossposting to twitter exactly because of this.
Technically is not hard, but I have to check if I wouldn't be risking getting tagged by twitter as spam again.

**Comment by stevenroose** [comment]
@renatolond ah so in a self-hosted instance it would be possible?

**Comment by stevenroose** [comment]
Then perhaps have a config setting "allow linking from twitter" and in case it's false, grey out the checkbox in the web page with the explanation that the instance disabled the feature. This way, users know that it's because of SPAM reasons and know they can get the feature by self-hosting :)

**Comment by knuxfanwin8** [comment]
How about putting the links through a link shortener like bit.ly? I'd say Twitter wouldn't ban users of common link shorteners, but I've never actually tried.

**Comment by renatolond** [comment]
As far as I can tell (from the experience with previous false positives in the crossposter), it seems twitter uses different filters, one of them being the app that's posting the links. That is, even though the crossposter posts link from different Mastodon and Pleroma instances, if they all look like `random.domain.com/@user/100000123456` or something slightly different in the case of pleroma, I do think it would be picked up as Spam by twitter automated detection.

I feel that the case of threads might be mitigated, but I'm not even sure it's the worst of it, though I don't have the numbers at hand.

In any case, my idea for this one is following what steven proposed, implementing it with a feature toggle to be enabled/disabled by the crossposter instance admin.

**Comment by saschafoerster** [comment]
> Either by setting a prefix or with a link to the original post in the suffix.

Or both! :) I was searching for this feature. I also want to show on every tweet, that it comes from a main-account on Mastodon. So I think it would be great to have just a prefix and a postfix, where you can add stuff like 
[Copy from Mastodon] or #Mastodon or the URL to the toot. 
The URL to the toot would maybe also only be needed, if the 280 signs are not enough.

**Comment by valerio-bozzolan** [comment]
Most of the people using Mastodon is interested in spreading Mastodon.

TBH just a footer with "Posted via Mastodon" is enough to make me happy.

**Comment by valerio-bozzolan** [comment]
Is anyone interested in having at least a "Posted via Mastodon" text in the footer, as temporary compromise?

**Comment by valerio-bozzolan** [comment]
> Is anyone interested in having at least a "Posted via Mastodon" text (without any link - to do not trigger Twitter anti-spam stuff) in the footer, as temporary compromise?

@stevenroose what do you think about?

**Comment by saschafoerster** [comment]
In the meantime, I started using N8N.io, so I can create postings in all different styles as I like them. Of course, I needed to create my own Twitter-app-secrets with API-access. #Workaround
