### ISSUE TITLE
Stop crossposting custom emojis to Twitter

### ISSUE THREAD

**Issue by ghost** [renatolond/mastodon-twitter-poster#165]
The Mastodon Twitter crossposter crossposts custom emojis (like :example:) to Twitter. Custom emojis don't show up on Twitter and as a result, they should not be crossposted.

**Comment by renatolond** [comment]
Hi!
What's your suggestion to do with the custom emojis? Remove them completely?

**Comment by its3ch0** [comment]
Yes, add an option to remove them from tweets.
- ec_ho

**Comment by arthurlogilab** [comment]
+1 for an option to remove them, or maybe an option to convert them into a hashtag ? 

`:debian:` would be converted to `#debian` ?

**Comment by renatolond** [comment]
Have to double check automation rules, most likely it's more safe to remove them instead of adding  hashtags

**Comment by Stopka** [comment]
+1
