### ISSUE TITLE
Sometimes uses get locked but not unlocked anymore

### ISSUE THREAD

**Issue by MichaelHierweck** [renatolond/mastodon-twitter-poster#166]
Sometimes uses get locked but not unlocked anymore. So after a while my instance is "dead" locked.
After releasing all locks via "update users set locked = false" all the pendings crosspostings are processed.

**Comment by mkody** [comment]
This happened to me too if Twitter returns this:
```
Twitter::Error::Forbidden: This request looks like it might be automated. To protect our users from spam and other malicious activity, we can't complete this action right now. Please try again later.
```
I might have to log in to Sidekiq and remove that job (because it will retry in a loop for a while) and then unlock the account to fix this.

**Comment by renatolond** [comment]
Hm, I'll add a way to access the sidekiq control panel, in the sidekiq control panel you can see which errors are keeping users in the locked state.

**Comment by renatolond** [comment]
I'm merging #167 in a moment, the idea is that you can make yourself admin, and then you can access `your.domain.com/sidekiq` to be able to get the status of the running jobs. With this you can debug why a user is stuck :)

**Comment by renatolond** [comment]
@MichaelHierweck did it help you?
