### ISSUE TITLE
twitter.activitypub.actor accounts undesirably show up when searching in Mastodon

### ISSUE THREAD

**Issue by jeroenpraat** [renatolond/mastodon-twitter-poster#171]
twitter.activitypub.actor accounts show up when searching in Mastodon. This is very confusing for Mastodon users, cause it looks like people can interact with those accounts (that they can not). I even searched for someone and their twitter.activitypub.actor account showed up first in the list.

The only way I could come up with for now is to suspend twitter.activitypub.actor. This works, but the only effect is that the Twitter mentions are not linked anymore (like before).

Hopefully this can be solved.

**Comment by renatolond** [comment]
twitter.activitypub.actor implements a fully fledged activitypub actor, which means it is indeed searchable. I don't think there's a way for them to be linked and not be searchable (nor the crossposter or twitter.activitypub.actor have control over user search on mastodon)

The only way I can see to avoid this is to avoid using twitter.activitypub.actor completely, which avoiding creating these users, but also not be linked, like before.

**Comment by jeroenpraat** [comment]
There are three possibilities:

1. Add an Activitypub setting for being searchable (and set to off for *.activitypub.actor accounts). This is actually a good generic privacy option as well. This must be done upstream Activitypub and *.activitypub.actor of course.
2. Every Activity project can blacklist *.activity.actor accounts (see Mastodon issue)
3. In Mastodon there is an option to mark your account as moved. This also removes from search. Maybe this can help the crossposter or  *.activitypub.actor upstream.

**Comment by jeroenpraat** [comment]
Yes maybe it's an idea to temporary disable twitter.activitypub.actor, until this is solved. But that is not my decision.

**Comment by renatolond** [comment]
I've disabled this on the crossposter side for now. I will turn this into a by-user configuration, disabled by default. Regarding how it appears on search and other things, it's indeed better to follow the Mastodon issue :)

**Comment by jeroenpraat** [comment]
Thanks Renato!
