### ISSUE TITLE
Feature request: Ability to link more accounts

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#18]
I'd really like to be able to link more accounts!

Like, at the moment I have my personal Twitter account linked to my personal Mastodon account. But I'd also really like to link my private Twitter to my private Mastodon account on Ephemeral, where toots disappear after a couple of hours. I also run an activism account on Twitter that I'd like to mirror to Mastodon with its own account.

They'd all be listed on [this page](https://crossposter.masto.donte.com.br/account):

![screen shot 2017-10-29 at 15 01 17](https://user-images.githubusercontent.com/6607512/32145034-0b207c3e-bcba-11e7-9c56-1928ad3dd436.png)

**Comment by renatolond** [comment]
Nowadays those connections are possible, they are just not be joined in a single profile (you'd have to sign out and then login with the other account to control the options). I think there's no clear sign out button, so I will start by doing that, and then I'll think on how multiple connections could be handled in a clear way :)

**Comment by Cassolotl** [comment]
A clear sign-out button would be helpful and a good compromise, I think! :) That was confusing me; I wasn't sure if signing out would disconnect everything and end the cross-posting.

**Comment by ardydo** [comment]
+1 for both this and the sign out button. I want to connect some other acounts but... I don't know how to sign out :D

**Comment by rx65m** [comment]
Is it possible to link several Twitter accounts to 1 Mastodon account?

**Comment by Cassolotl** [comment]
@rx65m,

>Is it possible to link several Twitter accounts to 1 Mastodon account?

This is like 4 years late but I just made this a feature request because I keep wanting it!

*[Feature request] Link multiple Twitter accounts to one Mastodon account #859*
