### ISSUE TITLE
Option to include tweet URL when posting from Twitter to Mastodon

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#19]
For the Twitter --> Mastodon option, would you consider adding an "include URL of original tweet" setting? Maybe just on tweets that have polls in them?

I post a lot of Twitter polls, which can cause confusion on Mastodon, and I think it would help for people on Mastodon to be able to click to open the Twitter poll!

**Comment by renatolond** [comment]
Would you prefer that the option enabled the URL in all tweets or only in polls?

**Comment by thiagomgd** [comment]
@renatolond I think it would make sense to be enable it only for polls.
Maybe having something like this

- [ ] Include original tweet link
    - [ ] Polls
    - [ ] Retweets
    - [ ] Quote retweets
    - [ ] Images
    - [ ] Regular tweets

**Comment by Cassolotl** [comment]
I think I would prefer it only in polls. It's the only thing I can think of where Twitter shows something that Mastodon can't copy.

**Comment by renatolond** [comment]
Yeah, me too, but I was just checking :)
Okay, it's on the queue, the idea will be to create a new option that will be disabled by default to enable twitter links when on polls :)

**Comment by Cassolotl** [comment]
Thank you! :)

**Comment by renatolond** [comment]
I have bad news :(
I was taking a look today on this one and there's no support for polls in the public twitter API: https://twittercommunity.com/t/poll-support/78235/8
I won't be able to fix this one for now :disappointed:

**Comment by Cassolotl** [comment]
Oh no, that's sad! Thank you for trying.

When I post a poll on Twitter and it gets cross-posted to Mastodon, I've been replying to the post on Mastodon with a link to the Twitter poll tweet, so it's not so bad really.

**Comment by renatolond** [comment]
I could still try to create an option to always post the tweet link, but since I cannot tell them apart it would always be there for "normal" tweets (not an RT, reply or quote)

**Comment by Cassolotl** [comment]
I think if that was an option I would probably just keep doing things the way I'm doing them now - I do polls much less often than normal tweets, and my normal tweets don't need URLs when crossposting.

**Comment by Cassolotl** [comment]
Just remembered something I saw in Tweetdeck once and tested it - somehow they have a way of detecting polls.

![screen shot 2017-11-25 at 11 15 26](https://user-images.githubusercontent.com/6607512/33229981-1f2c0ce8-d1d2-11e7-86bc-db577f9fdcd0.png)

I have no idea if whatever they do is possible with this crossposter, but I thought I'd mention it because it seems relevant and it might help? :S

**Comment by renatolond** [comment]
The thing is that I don't know if tweetdeck uses the public api, considering they are from twitter. The enterprise api (basically, premium api) has information about polls: 
http://support.gnip.com/enrichments/poll_metadata.html

So I think they might be using that one for tweetdeck, which would give them access to the poll information.

**Comment by Cassolotl** [comment]
@renatolond Ohhhh that makes sense! Damnit. :(
