### ISSUE TITLE
Authorized Applications - odd date.

### ISSUE THREAD

**Issue by DiagonalArg** [renatolond/mastodon-twitter-poster#198]
Under "Your authorized applications" in Framapiaf.org, I see:

```
Mastodon Twitter Crossposter 	read all your account's data
                                modify all your account's data 	Nov 09, 2017, 03:05 
```

That date is wrong.  I enabled the crossposter on July 20, 2019.  Other dates, eg. connection to Amaroq, are right.

**Comment by renatolond** [comment]
Hi!
The date is managed by mastodon, not the application. Unlike amaroq, the crossposter uses one application key per server, and then each user has their own personal token. So I think that might be the date the first user from framapiaf connected to the crossposter

**Comment by DiagonalArg** [comment]
Cool.  Thanks.  And thanks for your work.
