### ISSUE TITLE
Feature request: Ability to include replies-to-self

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#20]
Would it be possible to have a setting that lets me include replies-to-self? So, if I post on Twitter, and then reply to myself to make a thread, the reply will show on Mastodon - but if I reply to someone else, that *wouldn't* get cross-posted?

**Comment by renatolond** [comment]
Yeah, I'm working on allowing crossposting on both ways at the same time. With that change, I'll be also able to check if the reply of a given tweet/toot was crossposted and post the reply as a reply to the crossposted status as well. :)

**Comment by Cassolotl** [comment]
!!! 👍
