### ISSUE TITLE
Toots imported from Twitter don't have image URLs

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#21]
I'm not reporting a *problem* or anything, I guess it's just an inconsistency that I've spotted and I thought I should mention it in case it's a sign of a bug?

Toots imported from Twitter with images don't have image URLs:

![screen shot 2017-11-01 at 10 31 14](https://user-images.githubusercontent.com/6607512/32271024-11f20860-bef0-11e7-9d81-3724cb144e3a.png)

Toots with images directly uploaded *do* have image URLs:

![screen shot 2017-11-01 at 10 31 35](https://user-images.githubusercontent.com/6607512/32271036-1d920c92-bef0-11e7-94e3-d8065ebc9e69.png)

This is on Mastodon 2.0.0.

How does that work with federation? Does the image federate if there's no URL in the toot?

**Comment by thiagomgd** [comment]
It federates normally.
including the image url in the toot was a decision that gargron made some time ago, and he even asked again about this, because he's thinking of removing it (the link), as a lot of people just delete the link after adding the image.

**Comment by Cassolotl** [comment]
Ohhhh! Why is there an image URL at all, d'you know?

**Comment by renatolond** [comment]
Hi! The image URL is there in case you just post an image. Currently, Mastodon does not allow toots with no text. However, it's no limitation of the federation, but only a design decision.
On the crossposter side, I only post the image URL if there's no text, otherwise the URL is not posted. :)

**Comment by renatolond** [comment]
There was a PR which was not taken ahead for 2.0.0 which would remove the links from the web interface as well: https://github.com/tootsuite/mastodon/pull/5451
Anyways, it's not an issue for the moment, I might start posting ZWS when there's only images, but I won't make this change right now :)
