### ISSUE TITLE
Can't login to Mastodon

### ISSUE THREAD

**Issue by mkody** [renatolond/mastodon-twitter-poster#218]
Just upgraded my instance to `04ed4a3` but that was also the case on `8e067d2`. It's running at <https://crossposter.im-in.space/>.

When trying to login with a Mastodon account (tried with `im-in.space`, `mastodon.social` or `equestria.social`), we get an error page at <https://crossposter.im-in.space/users/auth/mastodon>.  
Here's the few lines I get on the server: 
```
Aug 25 13:06:56 crossposter bash[22163]: [b1fe5538-0da6-4794-b153-da0a94ae820c] Started POST "/users/auth/mastodon" for [snip] at 2019-08-25 13:06:56 +0000
Aug 25 13:06:56 crossposter bash[22163]: I, [2019-08-25T13:06:56.035429 #22163]  INFO -- omniauth: (mastodon) Request phase initiated.
Aug 25 13:06:56 crossposter bash[22163]: [b1fe5538-0da6-4794-b153-da0a94ae820c]
Aug 25 13:06:56 crossposter bash[22163]: [b1fe5538-0da6-4794-b153-da0a94ae820c] NoMethodError (private method `select' called for true:TrueClass):
Aug 25 13:06:56 crossposter bash[22163]: [b1fe5538-0da6-4794-b153-da0a94ae820c]
Aug 25 13:06:56 crossposter bash[22163]: [b1fe5538-0da6-4794-b153-da0a94ae820c] lib/mastodon_limited.rb:10:in `start_oauth'
```

Accounts already logged are running fine at least, and user can still use Twitter to login. But either adding a Mastodon account or using one to login fails.

**Comment by mkody** [comment]
I see this seems to be linked to the domain blocks, but I didn't set any `BLOCKED_DOMAINS` env.

**Comment by renatolond** [comment]
Ah, my bad! It should be fixed now, I forgot to add a test for no blocked domains :)

**Comment by mkody** [comment]
Thank you, I can confirm everything is working now!
