### ISSUE TITLE
Add option to use Nitter instead of Twitter

### ISSUE THREAD

**Issue by Booteille** [renatolond/mastodon-twitter-poster#233]
[Nitter](https://github.com/zedeus/nitter/) is an alternative front-end for Twitter.
Its purpose is to provide a privacy-friendly de-bloated interface.

You can try it on the main instance: https://nitter.net

I would love to see posts generated by your software using this tool, on Mastodon.
Would it be possible to add an option to do so.

Here are redirections you have to make:

`twitter.com`, `mobile.twitter.com` => `nitter.net` (or [any other instance](https://github.com/zedeus/nitter/wiki/Instances) the user choose
`pbs.twimg.com` => `nitter.net/pic/ENCODED_TWITTER_URL`
`video.twimg.com` => `nitter.net/gif/ENCODED_TWITTER_URL`

e.g;
`https://video.twimg.com/tweet_video/EEQUAt7WwAAlZmQ.mp4` becomes `https://nitter.net/gif/https%3A%2F%2Fvideo.twimg.com%2Ftweet_video%2FEEQUAt7WwAAlZmQ.mp4`

**Comment by renatolond** [comment]
Hi!
I don't know if the crossposter is the place with the most impact for this suggestion. Some mastodon forks replace `@twitter.com` mentions with an actual link and there it might have more impact.

We don't add links to twitter images or videos, when possible we crosspost the images themselves, only crossposting links in conditions when we failed to upload the media, due do an error on the instance of the user.

We do post the link to the original tweet, if the user wants, but only on retweets or quotes.

I don't mind adding this to the roadmap, but I haven't had a lot of time to work on new features for the crossposetr and it might take a while :)

**Comment by Booteille** [comment]
Thanks!

I am suggesting it because I see a lot of people retweeting things from Twitter with your tool!

I understand the lack of time, so don't worry about the time it takes.

Thanks you again!

**Comment by jeroenpraat** [comment]
+1

**Comment by jeroenpraat** [comment]
@renatolond I'm really looking forward to have this! :smiley: 

I already created a separate Nitter instance for newsbots.eu and also want to do that for todon.nl.

**Comment by raphgilles** [comment]
+1
Your tools is the most used for crossposting. It could be great to have the choice to configure a Nitter instance to replace the Twitter links.

**Comment by joachimesque** [comment]
+1 I would really like that option, too!

**Comment by Forceflow** [comment]
+1 This would be great!

**Comment by danielmunoz** [comment]
+1 Yes, please.
