### ISSUE TITLE
Is it possible for image descriptions for screen-readers to be cross-posted?

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#24]
I am not very knowledgeable about Twitter API things or Mastodon API things, but I just tested it and found that my image descriptions for screen-readers weren't copied from Twitter to Mastodon, nor the other way. So I thought I'd ask if it's possible to include image descriptions in cross-posting?

**Comment by renatolond** [comment]
Hmm. I'm not sure, but it should be possible. I'll make some tests and try to enable it :)

**Comment by Cassolotl** [comment]
Thank you! :)
