### ISSUE TITLE
Option to change the max. character limit for Mastodon

### ISSUE THREAD

**Issue by joenepraat** [renatolond/mastodon-twitter-poster#241]
I sometimes noticed that a quoted retweet was split in two toots. This is not needed on my server, cause we have a character limit of 1111.

So I was wondering if it's an idea to:

- Let a user set manually their character limit?

and/or ...

- automatically detect the servers character limit (like e.g. Tusky does).

**Comment by jeroenpraat** [comment]
Any update on this?

**Comment by shirishag75** [comment]
@renatolond looking forward to see what progress is being made on this. If we could have 1000 characters on mastadon vanilla it would make life much easier.

**Comment by renatolond** [comment]
@jeroenpraat not much, I'm afraid :(
Outside of updating dependencies I haven't worked a lot on the crossposter lately. I have a branch aging here where I started the work, but didn't advance much. Sorry!

**Comment by renatolond** [comment]
@shirishag75 This is just the crossposter, so we cannot increase the limit of chars in the vanilla mastodon. This will only support instances where the character limit is bigger than the standard 500 so that tweets and RTs are not split.
