### ISSUE TITLE
there doesn't seem to be one for mastadon.social ?

### ISSUE THREAD

**Issue by shirishag75** [renatolond/mastodon-twitter-poster#260]
I have an account on mastadon.social but there doesn't seem to be a way to use that. If I give it my e-mail id it gives a shrug and gives up. It did take my twitter profile and gave me option to authorize it. Maybe that needs work ?

**Comment by renatolond** [comment]
Hi! It does work for mastodon.social, you have to use your mastodon handle, that is, `username@mastodon.social`, let me know if you have further issues :)

**Comment by shirishag75** [comment]
I actually tried it multiple ways, I always get the following - 

![mastadon-error](https://user-images.githubusercontent.com/727626/68472059-937a7180-0217-11ea-92b9-fd1aacb4b023.png)

**Comment by shirishag75** [comment]
FWIW, the handle is the same shirishag75@mastadon.social

**Comment by renatolond** [comment]
There's an error in your handle, the correct address is `mastodon.social`, not `mastadon.social`, try with `shirishag75@mastodon.social` instead :)

**Comment by shirishag75** [comment]
oops, my bad. Drats. There was a reason I didn't like extinct mamooths, this was it ;)
