### ISSUE TITLE
My Twitter got 280 characters capacity last night and the crossposter hasn't caught on

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#27]
Last night my Twitter account got 280 characters - and today, even when I disconnected and reconnected my Twitter account on the crossposter, Mastodon posts over 140 characters are being cut short by the cross-poster on the way to Twitter.

Toot: https://cybre.space/@cassolotl/98968495994100895
Tweet: https://twitter.com/cassolotl/status/928218216064745473

No big deal, I'm not super grumpy about it, but it would be nice to take advantage of the extra space! :)

**Comment by renatolond** [comment]
Yeah, there's currently a hard 140-char limit, I looked into it when it was still in tests and there was no way to figure out if an account had 280 chars, so I was waiting for the full launch. Will be fixing it soon ;)

**Comment by Cassolotl** [comment]
Awesome! :) Thank you!

**Comment by Cassolotl** [comment]
Thank you @renatolond ! :)
