### ISSUE TITLE
Gifs are crossposted as videos

### ISSUE THREAD

**Issue by renatolond** [renatolond/mastodon-twitter-poster#28]
When a gif is posted to Mastodon, it is converted to an mp4(gifv). But when this is posted to twitter, it is shown as a video. (so it doesn't have gif autoplay)

**Comment by renatolond** [comment]
As a second part to this bug: Twitter only accepts videos longer than a certain length. So it means that when crossposting smaller gifs, twitter gives out an error of the kind 
`Duration too short, minimum:500, actual:140 (MediaId: snf: xxxx)`

**Comment by xylotism** [comment]
The reverse of this seems to be true -- videos posted to Twitter (with sound) are converted to GIF when sent to Masto (without sound)

**Comment by renatolond** [comment]
Do you have an example? I know mastodon converts mp4 without sound to gif automatically, but I never saw it doing with videos that had sound, and on the crossposter we don't do any extra processing.

**Comment by xylotism** [comment]
Disregard, I was wrong!
