### ISSUE TITLE
I've got blocked on mastodon.social for using this -> recommended instance list

### ISSUE THREAD

**Issue by novoid** [renatolond/mastodon-twitter-poster#294]
Hi!

Mastodon.social sent me an email, that my account "@publicvoit@mastodon.social has been limited". "The rule [I] most likely broke was crossposting retweets / quote tweets." Unfortunately, the three rules related to cross-posting are not that clearly written: https://mastodon.social/about/more I would not have guessed that I get in any problem by using the cross-poster as I did.

Since I don't want to limit the cross poster in order to maintain a synchronized Twitter/Mastodon universe, I'd love to see **a list of recommended instances or a list of instances with a table where I can easily see what cross-poster features are aligned with the current rules**.
 
This can be - of course - a crowd-sourced list where anybody is able to contribute. However, I do think that this cross-poster project is a good place to maintain this list. This way, I may choose wisely when I switch from mastodon.social to a different instance without getting issues again.

Thanks for your cool services!

**Comment by renatolond** [comment]
Hey, sorry about never answering to this.

I do not have the interest to keep a list of instances which allow for crossposting or linking to one from this project. I feel that most instances have clear enough rules about this, including mastodon.social current rules.
