### ISSUE TITLE
Guidance text in login form isn't fully visible

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#296]
![Screenshot 2019-12-31 at 22 56 48](https://user-images.githubusercontent.com/6607512/71635911-ef161980-2c20-11ea-899b-099cf89cdfa5.png)

I can't see the whole format so it's not clear how to log in.

**Comment by benpocalypse** [comment]
I also can't figure out what format this entry expects my mastodon identifier. The error text says "Please enter an email address." which also doesn't work.

I've tried @username@instance.domain as well as username@instance.domain and neither format seems to work. So, for now I can't connect my accounts.

**Comment by fdmarcin** [comment]
When I flipped my phone, I could see it expects `username@instance.com`.

I propose to only display this in the placeholder, and use "Your full Mastodon username" above the input field.

Placeholders should only show the preferred formatting: https://www.uiuxlibrary.com/field-placeholder/

@renatolond I'd be happy to work on this.

**Comment by renatolond** [comment]
I'd be happy to review it if you work on it, it's something I've been meaning to do for a while and indeed one of the most common issues users experience on the crossposter :)

**Comment by fdmarcin** [comment]
@renatolond To make sure - to update these strings should I make changes to `config/locales/en.yml`?
