### ISSUE TITLE
"Update user" --> "Save"

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#297]
This button on https://crossposter.masto.donte.com.br/user/advanced_twitter : 

![Screenshot 2019-12-31 at 22 59 06](https://user-images.githubusercontent.com/6607512/71635936-3bf9f000-2c21-11ea-9bb8-3a039816b7c0.png)

Its meaning is ambiguous and unintuitive, and I think the standard on this kind of page would just be "save" - it's a save button, right? Or if you wanted to use more words, maybe "save settings"?

**Comment by renatolond** [comment]
Hmm, I don't think I define the text on that button, I think rails does it for me, but I can change it to something else :)

**Comment by fdmarcin** [comment]
@renatolond I agree this would be a good change 👍 Or you could use "Save changes".
