### ISSUE TITLE
Error when connecting to Mastodon: We're sorry, but something went wrong

### ISSUE THREAD

**Issue by MathiasRenner** [renatolond/mastodon-twitter-poster#307]
I tried two different instances: https://crossposter.im-in.space/user/mastodon_identifier, and https://crossposter.masto.donte.com.br/

![image](https://user-images.githubusercontent.com/2377464/72686353-12333b00-3af4-11ea-8dd3-963f9dbd76e3.png)

Twitter works well, but Mastodon not with our instance on mastodon.bits-und-baeume.org
. On the Mastodon instance, there is not a single line of log even on debug log level.

Any ideas? Are there any settings on the Mastodon instance I should make sure they are correct?

**Comment by commagray** [comment]
Lol, same on my own instance. #306

**Comment by renatolond** [comment]
Hi!
This seems to be a different error than #306. I've tried to connect to mastodon.bits-und-baeume.org from the crossposter server and I get a timeout. The issue seems to be the ipv6 address of your server: https://ipv6-test.com/validate.php?url=mastodon.bits-und-baeume.org

**Comment by renatolond** [comment]
I'm closing this, but if you need more help just re-open :)

**Comment by MathiasRenner** [comment]
Thanks @renatolond for the reminder :-)

I did some tests again, and it seems that everything works now! This is so nice :smiley: !
We recently switched our mastodon instance to a new server, which works well with ipv6, so maybe that was the cause of the problem!
