### ISSUE TITLE
Crossposted boosts to Twitter are broken

### ISSUE THREAD

**Issue by commagray** [renatolond/mastodon-twitter-poster#309]
Instead of a link to original message it posts things like this:

![image](https://user-images.githubusercontent.com/27947961/73034829-c7e0ef80-3e4e-11ea-9839-e9eade65c040.png)

The link is https://ministry.moonbutt.science/users/commagray/statuses/103535373841820213/activity

**Comment by renatolond** [comment]
Hi!
I was looking into this and it seems to be a problem with Mastodon itself. Mastodon has an `uri` and a `url` fields in the response about a status. It used to be that they looked something like this:
```
   "uri"=>"tag:mastodon.xyz,2017-08-11:objectId=6901463:objectType=Status",
   "url"=>"https://mastodon.xyz/@renatolonddev/6901463",
```
Now, they both look like what you described:
```
 "uri"=>"https://masto.donte.com.br/users/renatolonddev/statuses/103537291371714140/activity",
 "url"=>"https://masto.donte.com.br/users/renatolonddev/statuses/103537291371714140/activity",
```

As it is, I can't seem to get the URL from the status itself.

**Comment by renatolond** [comment]
I will get the URL of the original toot instead, that will work in pleroma and mastodon :)

**Comment by guysoft** [comment]
This seems to be still broken - any way to debug it?

**Comment by renatolond** [comment]
@guysoft  This should've been fixed, do you have an example? Which instance of the crossposter are you using?

**Comment by guysoft** [comment]
boosted on tooot.im didn't show up on twitter.

**Comment by renatolond** [comment]
If you're using https://crossposter.masto.donte.com.br/, then boosts are disabled and will most likely not be re-enabled, due to https://github.com/renatolond/mastodon-twitter-poster/issues/164#issuecomment-456374895 
You can see that information in the homepage of the crossposter.
