### ISSUE TITLE
Garbage before mentions from Mastodon to Twitter

### ISSUE THREAD

**Issue by alyasirko** [renatolond/mastodon-twitter-poster#311]
![image](https://user-images.githubusercontent.com/27947961/73119904-babc2180-3f70-11ea-941d-124d6e8c17da.png)

Instead of just `🐘mle@derpy.email  🐘rf@mastodonsocial.ru` it adds `🐘profile@ministry.moonbutt.science` before it.

![image](https://user-images.githubusercontent.com/27947961/73119959-40d86800-3f71-11ea-9318-a0e0255a106d.png)

And using another crossposter instance at crossposter.im-in.space it just shows the wrong domain. It must be `@mle@derpy.email`, not my origin instance.

**Comment by renatolond** [comment]
Hey, the crossposter tries to find out the correct mention format by extracting parts from the mention in the status. I have managed to find a few different ones, but this one is not one of the known ones. I'll try to refine the regex to solve this issue, it's falling back to the "I don't know this format" regex, which reads everything after the `/` as the username.
