### ISSUE TITLE
Why is social.librem.one blocked?

### ISSUE THREAD

**Issue by jeremiahlee** [renatolond/mastodon-twitter-poster#315]
When trying to sign up, I am getting the error "Sorry, social.librem.one is blocked in this instance."

Why is this server blocked? Purism's [Librem One](https://librem.one/) is a great and affordable bundle of ethical services.

**Comment by renatolond** [comment]
Hi, librem is blocked due to their moderation decisions which go against masto.donte.com.br rules.

See https://social.libre.fi/notice/9iOsVYozfJTS9vBpNA and https://social.libre.fi/notice/9iZw5AqQ5qKjgFWm5Q
