### ISSUE TITLE
Twitter mentions on Mastodon do not convert to mentions on twitter

### ISSUE THREAD

**Issue by CrazyJake88** [renatolond/mastodon-twitter-poster#32]
Tried mentioning a twitter user on mastodon with the @username@twitter.com format and it looks like the crosspost saw the format but failed to convert it to a mention?

Toot: https://toot.chat/web/statuses/98987758829766514
Tweet: https://twitter.com/crazypedia/status/929450906667683841

![2017-11-11 16_26_48-toot](https://user-images.githubusercontent.com/1314033/32693744-e073b62e-c6fd-11e7-8dfe-6416a839881f.png)
![2017-11-11 16_26_25-crazypedia](https://user-images.githubusercontent.com/1314033/32693743-e0655dea-c6fd-11e7-91ab-a35aa2ed4c18.png)

**Comment by renatolond** [comment]
Yeah, this is a left-over from a previous twitter block, they blocked write access to the app and between their suggestions of what could've caused it, it was posting mentions, so I've disabled it #8. I'll try at some point re-enabling it and seeing what happens, but I'm afraid it could result in writing block again. 😞
