### ISSUE TITLE
Disable sending long toots as tweets

### ISSUE THREAD

**Issue by XenonFiber** [renatolond/mastodon-twitter-poster#33]
The link spam could get annoying if it happens too much, in my opinion. Either an option to disable sending those tweets or breaking them up into a chain could work a bit better.

**Comment by renatolond** [comment]
Hi!
You mean if a toot has more than the 280 chars of twitter, instead of sending part + link, you don't send it at all or break it down?

**Comment by XenonFiber** [comment]
Yeah, exactly.

**Comment by renatolond** [comment]
Okay, I always thought of this as a "tweetlonger" kind of thing from masto -> twitter, but I can add a "don't send toots over 280 chars" option :)

**Comment by XenonFiber** [comment]
Thank you :)
