### ISSUE TITLE
Avoid crossposting Keybase proof

### ISSUE THREAD

**Issue by fuglede** [renatolond/mastodon-twitter-poster#358]
This is a bit of a niche request, so feel free to deem it out of scope; in any case, here goes: On secure messaging service [Keybase](https://keybase.io), it is possible to "prove" ones identity by connecting it to ones web presence in various ways (see e.g. [my profile](https://keybase.io/fuglede) for a couple of examples).

For example, it is possible to verify your Twitter/Mastodon identities by creating posts in response to certain challenges created by Keybase. In the case of Mastodon, the result looks [like this](https://mastodon.social/@fuglede/103995485597838779). This post is really specific to Mastodon, so it being crossposted to Twitter doesn't make a lot of sense.

**Comment by renatolond** [comment]
Hey :)
I understand your request, but it seems a bit hard for me to block it without accidentally blocking user posts by consequence.
I also use keybase, but the post from keybase is posted in the user's language (mine for instance is in portuguese) so I can't match based on post content alone.
The post has no special app attached to it, so I can't detect by that either.

I could try to detect based on the url alone, but if keybase changes their URL for signatures, I guess I won't detect until someone comes to open a new issue.

Do you have any idea on regarding this?

**Comment by fuglede** [comment]
No, I agree with your concern. As a user, I would be happy if the matching was based on the strictest possible regular expression that will never match a legit user post but that would then break in the (perhaps likely but probably very rare) event that Keybase changes its protocol.

**Comment by renatolond** [comment]
Hey, since it seems Mastodon is deprecating the proofs https://github.com/mastodon/mastodon/pull/17045 , I'm dropping this one
