### ISSUE TITLE
Look into reducing permissions when posting in only one direction

### ISSUE THREAD

**Issue by renatolond** [renatolond/mastodon-twitter-poster#36]
When we connect accounts we always assume the user wants to post on both directions. Would be good to look into minimal permissions for the directions the user wants to enable.

**Comment by baptx** [comment]
Indeed, it looks a bit scary to ask so many permissions when I just want to retweet tweets from Twitter on Mastodon. I did not use the tool because of this issue:
```
This application will be able to:

    See Tweets from your timeline (including protected Tweets) as well as your Lists and collections.
    See your Twitter profile information and account settings.
    See accounts you follow, mute, and block.
    Follow and unfollow accounts for you.
    Update your profile and account settings.
    Post and delete Tweets for you, and engage with Tweets posted by others (Like, un-Like, or reply to a Tweet, Retweet, etc.) for you.
    Create, manage, and delete Lists and collections for you.
    Mute, block, and report accounts for you.
```

**Comment by renatolond** [comment]
Yeah, unfortunately twitter only has three permission types: "read", "read and write" and "read and write + direct messages" (from https://developer.twitter.com/docs/basics/apps/guides/app-permissions)
Mastodon is much more fine tuned, so I ask for just toots-related ones.
The idea here would be to only ask for read or write, but even so, it would probably still be a bit scary (since it would be half those lines there)

**Comment by baptx** [comment]
@renatolond why not add an option to only "read" Twitter? This would be enough for people who just want to retweet tweets from Twitter to Mastodon. It should even be possible without the read permission on Twitter if the tweet is public since it is not needed to log in to read it.

**Comment by renatolond** [comment]
Yeah, that's the whole idea of this task, but it involves changing a bit how the crossposter works so that you chose first what you want to do and then connect your accounts.
