### ISSUE TITLE
Gives me 404 error when trying to Link my mastodon account. 

### ISSUE THREAD

**Issue by CloverTravels** [renatolond/mastodon-twitter-poster#379]
<img width="1440" alt="Screen Shot 2020-05-25 at 11 14 28 AM" src="https://user-images.githubusercontent.com/65918285/82835447-e85e9c00-9e78-11ea-8331-1b427f3329ef.png">

**Comment by renatolond** [comment]
It seems you're using your email to try to login, you should use your mastodon user + instance, like `handle@mastodon.social`

**Comment by CloverTravels** [comment]
ah okay, thank you!!
