### ISSUE TITLE
It seems you're using your email to try to login, you should use your mastodon user + instance, like `handle@mastodon.social`

### ISSUE THREAD

**Issue by CloverTravels** [renatolond/mastodon-twitter-poster#380]
I closed this issue too soon. I just tried to use the mastodon user handle of mine "@Clovertravels@switter.at" and it didn't work either. 

"It seems you're using your email to try to login, you should use your mastodon user + instance, like `handle@mastodon.social`

_Originally posted by @renatolond in https://github.com/renatolond/mastodon-twitter-poster/issues/379#issuecomment-633679707_'"

**Comment by CloverTravels** [comment]
![IMG_8099](https://user-images.githubusercontent.com/65918285/82837908-6625a600-9e7f-11ea-9dad-a0fd448564c8.PNG)

**Comment by CloverTravels** [comment]
<img width="1440" alt="Screen Shot 2020-05-25 at 11 59 58 AM" src="https://user-images.githubusercontent.com/65918285/82837931-750c5880-9e7f-11ea-999b-7f4e42b89a11.png">

**Comment by renatolond** [comment]
Sorry, I need to fix that validation, the message is wrong, but the format is right, try `Clovertravels@switter.at`

**Comment by CloverTravels** [comment]
Thank you!! That worked!
