### ISSUE TITLE
Add a link to the status checker graphs on the homepage

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#44]
This is the page I mean: https://metrics.librato.com/s/public/241h4bwu2?duration=21600

Having a link to that page might help prevent "why isn't my tweet posting????" questions in future.

Also, since there is sometimes a delay/backlog, maybe a thing saying how long you might have to wait until your post is cross-posted might be cool?

This is all pretty non-urgent but I was wondering about status stuff today and wondering why my tweet wasn't being cross-posted (it was my fault XD) and these things would have been pretty helpful to have in an easy-to-find place! :)

**Comment by renatolond** [comment]
The link to the page is a good idea, I'll try to do that ASAP :)
I could try to estimate the delay based on how long it's taking, I'll try to think on how to do that, thanks for the idea!
