### ISSUE TITLE
Tags with dots right in front of them on Twitter don't get crossposted correctly to Mastodon

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#45]
![screen shot 2017-11-25 at 14 37 43](https://user-images.githubusercontent.com/6607512/33231508-396790f2-d1ee-11e7-9f30-058e2add5c9b.png)

Putting a dot before tags is pretty common on Twitter, but when I do that it breaks the cross-posting. It's totally not urgent and I can work around it, but I thought I should mention it!

**Comment by renatolond** [comment]
I forgot to answer you on this one!
Is this coming from mastodon or twitter?
I tested with twitter and the mention is indeed weird. I've created a PR, if it's the only thing that you saw wrong, I'll close it :)

**Comment by Cassolotl** [comment]
@renatolond Yeah, it's when posts go from Twitter to Mastodon, with the tweet coming first! :)

Also thanks!
