### ISSUE TITLE
All looks fine but no toots are posted from Mastodon to Twitter

### ISSUE THREAD

**Issue by jacotec** [renatolond/mastodon-twitter-poster#483]
After hours of checking around I think my last resort is to open an issue.

My bridge is healthy and I've updated to the very latest version today. Twitter and Mastodon account are connected and I've configured my bridge to post all type of toots to Twitter without limitation. Sidekiq is running and I see the "mastodonbridge" process live in Sidekiq.

But whatever I post in Mastodon - nothing appears in my Twitter account. Syslog does not show me anything here and I don't see additional log files which could help me (There is a "production.log" and a "development.log" in /home/crossposter/live/log, but they are both dated 2019 and quite empty).

Is there a general issue with this project, or what can I do to track this down?

**Comment by renatolond** [comment]
Hi!
The process outputs to the standard out, so it should be logged to your syslog instead (if you use it), in my setup for instance I can see the logs with `journalctl --follow -u crossposter-sidekiq`

One extra thing to check, if you visit `https://<your-host>/sidekiq/recurring-jobs`, has the check_for_statuses_scheduler ran recently?

**Comment by jacotec** [comment]
Hi Renato,

the recurring-jobs shows the "check_for_stauses_scheduler" running every minute.

I've posted a test toot at 14:32:00 UTC. The syslog is completely silent until 14:35:06 where these messages started:

```
Jan 14 14:35:06 mastodonbridge bundle[3118]: [e27c27fb-d9db-401d-aee2-0fc505ea2d12] Started GET "/sidekiq/recurring-jobs?poll=true" for 10.0.0.1 at 2021-01-14 15:35:06 +0100
Jan 14 14:35:06 mastodonbridge bundle[3118]: [e27c27fb-d9db-401d-aee2-0fc505ea2d12]   #033[1m#033[36mUser Load (0.9ms)#033[0m  #033[1m#033[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2#033[0m  [["id", 2], ["LIMIT", 1]]
Jan 14 14:35:06 mastodonbridge bundle[3118]: `Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/home/crossposter/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-scheduler-3.0.1/lib/sidekiq-scheduler/redis_manager.rb:99:in `block in schedule_exist?')
Jan 14 14:35:07 mastodonbridge bundle[3118]: [fb24e203-0127-435a-ad9d-862c48a35b49] Started GET "/sidekiq/images/favicon.ico" for 10.0.0.1 at 2021-01-14 15:35:07 +0100
Jan 14 14:35:07 mastodonbridge bundle[3118]: [fb24e203-0127-435a-ad9d-862c48a35b49]   #033[1m#033[36mUser Load (0.6ms)#033[0m  #033[1m#033[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2#033[0m  [["id", 2], ["LIMIT", 1]]
Jan 14 14:35:09 mastodonbridge bundle[3118]: [2068487d-437e-40d7-ae99-531960132f70] Started GET "/sidekiq/recurring-jobs" for 10.0.0.1 at 2021-01-14 15:35:09 +0100
Jan 14 14:35:09 mastodonbridge bundle[3118]: [2068487d-437e-40d7-ae99-531960132f70]   #033[1m#033[36mUser Load (0.7ms)#033[0m  #033[1m#033[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2#033[0m  [["id", 2], ["LIMIT", 1]]
Jan 14 14:35:09 mastodonbridge bundle[3118]: `Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/home/crossposter/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-scheduler-3.0.1/lib/sidekiq-scheduler/redis_manager.rb:99:in `block in schedule_exist?')
Jan 14 14:35:11 mastodonbridge bundle[3118]: [a204a3e0-c637-446a-86d1-6f55d59982e5] Started GET "/sidekiq/recurring-jobs" for 10.0.0.1 at 2021-01-14 15:35:11 +0100
Jan 14 14:35:11 mastodonbridge bundle[3118]: [a204a3e0-c637-446a-86d1-6f55d59982e5]   #033[1m#033[36mUser Load (0.6ms)#033[0m  #033[1m#033[34mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2#033[0m  [["id", 2], ["LIMIT", 1]]
Jan 14 14:35:11 mastodonbridge bundle[3118]: `Redis#exists(key)` will return an Integer in redis-rb 4.3. `exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. (/home/crossposter/live/vendor/bundle/ruby/2.6.0/gems/sidekiq-scheduler-3.0.1/lib/sidekiq-scheduler/redis_manager.rb:99:in `block in schedule_exist?')

```

These repeat every 2 seconds, filling up my syslog now.

I'm wondering about the IP 10.0.0.1 in these messages, that's my gateway IP - why does it appear in these lines?

`Jan 14 14:35:06 mastodonbridge bundle[3118]: [e27c27fb-d9db-401d-aee2-0fc505ea2d12] Started GET "/sidekiq/recurring-jobs?poll=true" for 10.0.0.1 at 2021-01-14 15:35:06 +0100`

**Comment by renatolond** [comment]
Those seems like the logs for the web side of the crossposter, you should have logs for the sidekiq process too. If you only have those, it probably means your sidekiq process didn't start correctly, if you followed the [setup in the readme](https://github.com/renatolond/mastodon-twitter-poster#setup), make sure the second service is correctly setup :)

**Comment by jacotec** [comment]
The service file is exactly identical up to the ExecStart line, The original line "ExecStart=/bin/bash -lc "bundle exec sidekiq -c 5 -q default" does not work and produces an error:

`Jan 14 15:04:24 mastodonbridge bash[4988]: /bin/bash: bundle: command not found
`
My service file looks like this:
```

[Unit]
Description=mastodon-twitter-crossposter-sidekiq
After=network.target

[Service]
Type=simple
User=crossposter
WorkingDirectory=/home/crossposter/live
Environment="RAILS_ENV=production"
Environment="RAILS_LOG_TO_STDOUT=enabled"
Environment="RAILS_MAX_THREADS=5"
ExecStart=/home/crossposter/.rbenv/shims/bundle exec sidekiq -c 5 -q default
TimeoutSec=15
Restart=always

[Install]
WantedBy=multi-user.target
```

**Comment by jacotec** [comment]
When I start sidekiq manually with

`RAILS_ENV=production bundle exec sidekiq
`
I see once per minute this output on the shell (I guess that's the status checker task):

`User Load (0.9ms)  SELECT "users".* FROM "users" WHERE (locked = FALSE AND (posting_from_mastodon = TRUE OR posting_from_twitter = TRUE) AND (mastodon_last_check < now() - interval '30 seconds' or twitter_last_check < now() - interval '30 seconds')) ORDER BY "users"."mastodon_last_check" ASC, "users"."twitter_last_check" ASC
`

So something is done once per minute - but still posts are not handled.

**Comment by renatolond** [comment]
That's odd, do you have access to your db? Can you check what your user is looking like?
specifically, what you have in `locked`, `posting_from_mastodon`, `posting_from_twitter`, `mastodon_last_check`, `twitter_last_check` ?

**Comment by jacotec** [comment]
Sure, it's a VM on my server. Do you have the commands by your hand? I'm not a deep Posgres expert and would need to google all ;-)

**Comment by renatolond** [comment]
You should have psql to access the db, you can use it with
`psql <db name>` , if you didn't override it, `psql mastodon_twitter_poster_production`
Then, in the prompt:
`select locked, posting_from_mastodon, posting_from_twitter, mastodon_last_check, twitter_last_check from users;`

**Comment by jacotec** [comment]
This is the output:

```
crossposter=# select locked, posting_from_mastodon, posting_from_twitter, mastodon_last_check, twitter_last_check from users;
 locked | posting_from_mastodon | posting_from_twitter |    mastodon_last_check     |     twitter_last_check     
--------+-----------------------+----------------------+----------------------------+----------------------------
 t      | t                     | t                    | 2019-08-24 07:32:00.493229 | 2019-08-24 07:32:00.435212
(1 row)
```

Should I reinit the database maybe? I can restore my settings easily.

**Comment by renatolond** [comment]
Okie, your account is marked as "locked", that's why: when sidekiq takes an account to process, it locks the account and when it finishes the checks, it unlocks it. It could happen that your server had a power surge or some other thing that caused sidekiq to die without having time to unlock the account. The easiest way to fix it is to go to `https://<your-host>/account`, disconnect both Mastodon and Twitter, logout and then login again with both services. That should create a new account which will not be locked.

Another option, if there's no jobs in `https://<your-host>/sidekiq/queues` or `https://<your-host>/sidekiq/morgue`, is to update your account with:
`update users set locked = false' (since you only seem to have one user on your db, I'm not using a where here, but if you do, you have to set your user id)

**Comment by jacotec** [comment]
OK, I'll try to unlock my user in the DB.

BTW: Meanwhile I took a snapshot and tried to reinit the database. Was the command for this changed without updating the docs? When I give the command, I'm getting an error message:

```
crossposter@mastodonbridge:~/live$ bundle exec rake db:setup                             
rake aborted!
LoadError: Could not load the 'listen' gem. Add `gem 'listen'` to the development group of your Gemfile
/home/crossposter/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/home/crossposter/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/home/crossposter/live/vendor/bundle/ruby/2.6.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:89:in `register'
....

```

Interesting is that it wants to use Ruby 2.6.0 although 2.6.5 is installed due to the requirements of the current version.

**Comment by renatolond** [comment]
It was not changed, but you might need to use `RAILS_ENV=production bundle exec rake db:setup` depending on your setup, I'll upgrade the docs to be on the safe side :)

**Comment by jacotec** [comment]
I've unlocked the user and now it's working again! Thank you very much for your help! :-)

(Still interesting why the DB setup command does not work ...)

**Comment by jacotec** [comment]
@renatolond Still thinking of this and how that could be prevented ... What about a kind of a "Watchdog" which detects a lock lasting for a certain time and releases it automatically when it got stuck?
And/or displaying this state in the webserver with the option to manually unlock it?

Clearing all locks on server start?

Other than that your crossposts are stopped working, you'll not get aware of this state.

**Comment by renatolond** [comment]
Yeah, I have to think a bit about this, there's other reasons for a job to get stuck which I wouldn't want to clear manually (such as, if your server is down for too long, the job will be moved to the dead jobs queue, and it doesn't get out of there manually)
But I do think there's a way to clear out this on boot without touching those and in any case I think I need to document those for troubleshooting :)
I'll open a separate issue for those two :)
