### ISSUE TITLE
Clear locked jobs on sidekiq server start?

### ISSUE THREAD

**Issue by renatolond** [renatolond/mastodon-twitter-poster#506]
In certain cases it can happen that a job got into a stuck state (server reboot during the job execution and so on) and it's lock was never released.
One way to fix this would be to check locked users on sidekiq boot and unlock them. Need to make sure this does not conflict with current strategy of adding jobs to the queues. Cannot unlock dead jobs.

Relates to #483

**Comment by HugoPoi** [comment]
Do we need a lock per user in db ?
Can we have a recurring task per user instead ? Sidekiq support lock per job no ?

**Comment by renatolond** [comment]
How would you suggest a recurring task per user? I'm not aware of a way to locking per job using sidekiq

**Comment by HugoPoi** [comment]
> How would you suggest a recurring task per user?

I think yes.
