### ISSUE TITLE
when mastodon WEB_DOMAIN different from LOCAL_DOMAIN

### ISSUE THREAD

**Issue by fivestone** [renatolond/mastodon-twitter-poster#517]
Sometimes the mastodon the user id is like **@user@domain.com** but the web interface is **subdomain.domain.com**.

When the crossposter connect to mastodon the user id need to be filled as user@subdomain.domain.com , then the connection still works. 

It's not a bug, but I think it would be better to have some notes on the connecting page.

**Comment by jeroenhabets** [comment]
@fivestone I was bit by this today but thanks to your info I got it working 👍 .

**Comment by Duke-Igthorn** [comment]
I just ran into this issue as well on my own server. Glad that the subdomain name works!
