### ISSUE TITLE
Add a way for users to "opt-out" of having their toots boosted on Twitter.

### ISSUE THREAD

**Issue by renatolond** [renatolond/mastodon-twitter-poster#55]
Even though it's not possible to post actual content from Mastodon on Twitter (since the only boost option is "boosted: <link>") there might be users that do not want their toots to go even so far as being in that case.
Create a way for users to ask to block their toots from interacting with the crossposter.

**Comment by twilde** [comment]
Wouldn't using one of Mastodon's privacy options, which prevent boosting, be the best bet in this case? It's still equally trivial to simply tweet a link to a Masto post if it's public, exactly identical to cross-posting a boost.

**Comment by renatolond** [comment]
That's currently the case. Even so, I can see cases in which users want to opt-out entirely of being cross-posted, even if they are okay with their content being public on Mastodon. This feature is more for this case :)
