### ISSUE TITLE
CW + media seems bugged

### ISSUE THREAD

**Issue by OniriCorpe** [renatolond/mastodon-twitter-poster#551]
Hi!

Crosspost from fedi to twitter doesn't post medias like pictures when there is a CW

**Comment by nevillepark** [comment]
I also experience this. Now that Twitter has added the option to mark individual tweets with media as sensitive, perhaps it's now easier to fix this?

**Comment by nevillepark** [comment]
**Update:** did some digging and I think this is the relevant crossposter code:

https://github.com/renatolond/mastodon-twitter-poster/blob/27bb71e7a18eba8f4eeaafaa1cd9bef14633f302/lib/mastodon_user_processor.rb#L388

or maybe this bit:

https://github.com/renatolond/mastodon-twitter-poster/blob/27bb71e7a18eba8f4eeaafaa1cd9bef14633f302/lib/mastodon_ext.rb#L42

On the Twitter end, ["possibly_sensitive"](https://developer.twitter.com/en/docs/twitter-api/v1/data-dictionary/object-model/tweet) would be the tweet attribute to add: 

> `possibly_sensitive` | Boolean | Nullable. This field only surfaces when a  Tweet contains a link. The meaning of the field doesn’t pertain to the  Tweet content itself, but instead it is an indicator that the URL contained in the Tweet may contain content or media identified as  sensitive content. Example: `"possibly_sensitive":false`

(It's in the v2 API as well.)

As per [this post](https://twittercommunity.com/t/ways-to-stop-minimise-processing-sensitive-media-with-the-api/147224/3) it should apply to attached media as well. However I am not A Programmer™ and don't have the wherewithal to go about testing it.

**Comment by Psycojoker** [comment]
I'm pretty sure you just need to remove the `unless toot.sensitive?` here to fix this:

https://github.com/renatolond/mastodon-twitter-poster/blob/b09bec72ae67a4b6c2c30e3fec08d04356831529/lib/mastodon_user_processor.rb#L267

Or use new sensitive media twitter function

**Comment by nevillepark** [comment]
Maybe both?
