### ISSUE TITLE
crosspost to 2 account

### ISSUE THREAD

**Issue by J0hsHH** [renatolond/mastodon-twitter-poster#565]
is it posible to crospost to both a mastadon account and a pleroma at the same time 

twitter to mastadon
twitter to pleroma

**Comment by renatolond** [comment]
Hi, @J0hsHH, I don't plan on allowing multiple accounts to be linked. The idea is that you can link your personal twitter account to your fediverse account (and if you want to share to another account, you could boost the first one)
