### ISSUE TITLE
Incorrect @username handling from Twitter -> Mastodon

### ISSUE THREAD

**Issue by poshaughnessy** [renatolond/mastodon-twitter-poster#57]
Hello. Firstly, thank you very much for this service!

I had an issue with [my tweet today](https://twitter.com/poshaughnessy/status/941275544150315008). It @ mentioned "brucel" (with an 'l'). But the [toot posted to Mastodon](https://toot.cafe/web/statuses/99172529594083946) replaced this with "@bruce@twitter.coml", i.e. it moved the "l" after "twitter.com".

**Comment by renatolond** [comment]
Hm, weird one, but it's not the first time the Twitter conversion has given weird results 😞 
I'll take a look, thanks for reporting!
