### ISSUE TITLE
RSS feed as source?

### ISSUE THREAD

**Issue by poVoq** [renatolond/mastodon-twitter-poster#589]
Would it be possible to post to both Twitter and Mastodon from an RSS feed as the source?

Thanks for considering.

**Comment by renatolond** [comment]
Hey @poVoq :)
Sorry for the delay answering this. This is out-of-scope for this project, the idea is really to post from one to the other. However, you could achieve that by using another tool that posts from an RSS to one of the two and then use the crossposter to do the posting between them. I don't have any tool in mind though.
