### ISSUE TITLE
For retweets ported Twitter→Mastodon, consider putting the text of the retweet before the link too

### ISSUE THREAD

**Issue by jancborchardt** [renatolond/mastodon-twitter-poster#59]
Otherwise it looks very bland and untrustworthy in the feed:
![screenshot from 2017-12-15 13-42-42](https://user-images.githubusercontent.com/925062/34042618-db303600-e19d-11e7-9474-f946f392636e.png)

In the profile view it looks ok with the embedded tweet, but most logged in people probably never see this: https://mastodon.social/@opensourcediversity/99178310987812450

**Comment by renatolond** [comment]
Hi, Jan!
Would that be part of the text (as an introduction, click the link for more) or the full text of the retweet?

**Comment by jancborchardt** [comment]
Full text would be ideal. Like:

> RT: "Full text of what the other person wrote" https://twitter.com/…


Thank you for the great tool! :)

**Comment by jancborchardt** [comment]
Thanks a lot! :)
