### ISSUE TITLE
Twitter → Mastodon crossposts no longer include image, only link

### ISSUE THREAD

**Issue by nevillepark** [renatolond/mastodon-twitter-poster#597]
Just noticed this today. [A tweet with attached image](https://twitter.com/neville_park/status/1448753694732869635) crossposts [without the image](https://bananachips.club/@nev/107102098232537184), only the media URL. 

This occurs with an Android client as well as Tweetdeck on web.

**Comment by nevillepark** [comment]
Thank you for responding so fast! I checked the timeline and it turns out we actually moved to a new server, so that probably caused it.

It's still happening, though ([example](https://bananachips.club/@nev/107108982968369158)). Will reach out to the admin to see if everything's working fine—I don't know anything about how it works behind the scenes.

**Comment by Danie10** [comment]
A few days back, all my posts from Twitter to Mastodon (@danie10@mastodon.social) started doing the same thing. Image is just lost, where it was always including the image before.

**Comment by renatolond** [comment]
@Danie10 It seems there's a lot of timeout errors coming from mastodon.social, in that case it will happen the same as I said above: 
> When I designed this part of the crossposter, I decided to do it a bit resilient and have a fallback, since it can happen that an image is too big to be posted to Mastodon or something like that, and in that case, I still post a link back to the original media, but I do not retry.

Contact your admin to double check for the slowdown, it probably will fix your issues. If you still have issues, open a new issue and we can follow it up :)
