### ISSUE TITLE
CROSS POSTER NOT WORKING - "invalid credentials"

### ISSUE THREAD

**Issue by avamiu** [renatolond/mastodon-twitter-poster#598]
i'm at https://crossposter.masto.donte.com.br/ - my twitter appears connected but when i try to connect my mastodon name "avamiu@switter.at" i get the message "invalid credentials." i've even tried making a new account and connecting it there. no use. please help!

**Comment by renatolond** [comment]
Hey, since switter.at is closing down, I'm closing this, if you need help again just re-open!
