### ISSUE TITLE
Add wordlists to white- or blacklist cross-posting

### ISSUE THREAD

**Issue by twilde** [renatolond/mastodon-twitter-poster#60]
The use case I have in mind is to block all posts containing `\btoot\b` from going from Mastodon -> Twitter because they will probably confuse the poor Twitterers who don't understand Masto, but I could imagine tons of more complicated things one could do with regex-based black- and whitelisting.

**Comment by renatolond** [comment]
Hi!
I think having word lists to avoid crossposting is a good idea, but I'm not so much into the idea of regexes for that end, since the average user doesn't know how they work. Do you think word lists would solve your problem? :)

**Comment by twilde** [comment]
Yeah, word lists would be sufficient, thanks!

**Comment by Cassolotl** [comment]
Oh gosh I would love this! I would just add a little thing like... `[dnc]` (do not crosspost), and when I write that in a tweet or toot it wouldn't crosspost. YEAH.

**Comment by joshuatj** [comment]
+1 would love to have a finer control on cross-posting. Right now the only option seems to be flipping the on/off switch every time I do not want to cross-post.

**Comment by nevillepark** [comment]
I'd also really appreciate this feature. I previously used IFTTT for this, which lets you selectively tweet items from an RSS/Atom feed (which Mastodon generates for your public toots) that contain a particular hashtag or word. However the IFTTT API is...problematic, and replicating this in the crossposter would be great.

**Comment by Cassolotl** [comment]
omg awesome <3

**Comment by nevillepark** [comment]
Thank you!
