### ISSUE TITLE
Include image alt text in cross-posts

### ISSUE THREAD

**Issue by jmacmahon** [renatolond/mastodon-twitter-poster#604]
Image alt text is currently not included when crossposting and it would be nice if it was :)

Not sure how to deal with varying character limits, but maybe just trimming and adding "[...]" like is done with posts?

**Comment by renatolond** [comment]
Can you give me some more info, what is the issue you're seeing, exactly?
As far as I can see on my tests, alt text is being correctly posted both ways, I've tested it recently

**Comment by jmacmahon** [comment]
Turns out this was a problem with my Mastodon instance, sorry to bother you.
