### ISSUE TITLE
[Feature Request] Option to not crosspost any tweet that contains a twitter @mention -update twitter word list option?

### ISSUE THREAD

**Issue by p0sty** [renatolond/mastodon-twitter-poster#606]
I would like to make sure that the content that I write and create gets posted to the fediverse, but not content where I'm interacting with other twitter users. Most of the time for me that tends to be interactions with brands and I don't want that on the masto feed. 

I tried adding "@twitter.com" to my words list not to copy, but because this is generated by the masto crossposter it's not included in the list when i try (yes i clicked the save and also the update user button before posting). 

example here: 
https://aus.social/@Posty/107517574588343262
https://twitter.com/posty/status/1475358800643182592?s=20

it just crossposts anyway. 

I've looked through the issues and I can't seem to find any that fit.

Given that resolving who people are is a [non-trivial problem](https://github.com/renatolond/mastodon-twitter-poster/issues/160), it should be an option to just not worry about it.

**Comment by nevillepark** [comment]
Does adding only "@" to the word list work? 

(This is obviously kind of hacky and wouldn't work if you tend to use @ as short form for "at" a lot.)

**Comment by p0sty** [comment]
I've added just the character:

@

to my wordlist and so far it looks like it's working!

smart thinking!

it's a hack, but a good one.

**Comment by mochsner** [comment]
@p0sty  curious if you could even add " @" to only disclude it when preceded by a space? (the wordlist might parse that space out, though...)

**Comment by mochsner** [comment]
Hey @p0sty you ever try the preceding space to see if that works?

**Comment by p0sty** [comment]
@mochsner I have not yet, but i'm not sure i want to, because i often start tweets with an @ :)
This has worked really well stopping what i call 'cross-pollination'.
it's fine for stopping twitter content going over the barrier, a valid instead of  @ is to use hashtags as they are on both networks.
