### ISSUE TITLE
Help with nginx for docker install

### ISSUE THREAD

**Issue by timconsidine** [renatolond/mastodon-twitter-poster#607]
I've installed with docker as per instructions on self-hosted VPS
Containers are running but I get 502 bad gateway
I have setup a nginx for the domain using the example in util/nginx.conf
I will add HTTPS with certbot after the base install works

**Comment by timconsidine** [comment]
Looks like it is related to not finding db on localhost:5432 
Investigating

**Comment by renatolond** [comment]
Did you manage to fix this?

**Comment by renatolond** [comment]
I'm closing this, but you're welcome to reach out again if you still need help :)
