### ISSUE TITLE
yarn install --pure-lockfile

### ISSUE THREAD

**Issue by timconsidine** [renatolond/mastodon-twitter-poster#608]
When installing w/o Docker in a LXC container, I'm getting :
```
Usage: yarn [options]

yarn: error: no such option: --pure-lockfile
```

`yarn install --help` shows no options for `--pure-lockfile`

Ubuntu 20.04 with apt update && apt upgrade done

**Comment by renatolond** [comment]
What is your `yarn` version?  (from `yarn --version`)

**Comment by renatolond** [comment]
I'm closing this, if you need more help please re-open!
