### ISSUE TITLE
mstdn.io is blocked

### ISSUE THREAD

**Issue by rcsilva83** [renatolond/mastodon-twitter-poster#618]
I'm trying to setup the Crossposter with my Mastodon account (rcsilva83@mstdn.io) but I get the following error:

`Sorry, mstdn.io is blocked in this instance. `

Why is it blocked? Would it be possible to unblock it?

Thank you very much!

**Comment by renatolond** [comment]
Hi :)

> If you just want to use it, there's one running at https://crossposter.masto.donte.com.br, which you can use from most Mastodon servers (except the ones suspended at masto.donte.com.br).

And `mstdn.io` is silenced over at masto.donte.com.br: https://masto.donte.com.br/about/more

There are other instances and other crossposters you can use, but my instance follows the list of blocked servers from masto.donte
