### ISSUE TITLE
error: no route matches [GET] "/sign_out"

### ISSUE THREAD

**Issue by rriemann** [renatolond/mastodon-twitter-poster#638]
Hello!

I am still testing my Docker setup with Mastodon and Crossposter. Both speak now to each other. I have done the login with the crossposter admin account via Mastodon only (not Twitter). When I click on log out, I get the following error:

![Screenshot_20220206_035608](https://user-images.githubusercontent.com/111932/152666130-4259e9ab-740c-4eec-b848-bcb7ab0cdf9c.png)

At the same time, the application log shows:

~~~
crossposter-web  | I, [2022-02-06T02:55:54.326853 #1]  INFO -- : [da43674e-ffb3-4de2-95ed-1b8a6b9a1513] Started GET "/sign_out" for 85.26.6.118 at 2022-02-06 02:55:54 +0000
crossposter-web  | F, [2022-02-06T02:55:54.330251 #1] FATAL -- : [da43674e-ffb3-4de2-95ed-1b8a6b9a1513]   
crossposter-web  | [da43674e-ffb3-4de2-95ed-1b8a6b9a1513] ActionController::RoutingError (No route matches [GET] "/sign_out"):
crossposter-web  | [da43674e-ffb3-4de2-95ed-1b8a6b9a1513]   
~~~

The Caddy proxy access log has:

```json
{
  "level": "error",
  "ts": 1644116154.3321428,
  "logger": "http.log.access.log1",
  "msg": "handled request",
  "request": {
    "remote_addr": "[redacted]:54766",
    "proto": "HTTP/2.0",
    "method": "GET",
    "host": "[redacted]pilot.host",
    "uri": "/sign_out",
    "headers": {
      "Cookie": [
        "_mastodon_twitter_poster_session=tLDPnblWD[redacted]"
      ],
      "Sec-Fetch-Dest": [
        "empty"
      ],
      "Sec-Fetch-Site": [
        "same-origin"
      ],
      "Te": [
        "trailers"
      ],
      "User-Agent": [
        "Mozilla/5.0 (X11; Linux x86_64; rv:96.0) Gecko/20100101 Firefox/96.0"
      ],
      "Accept": [
        "text/html, application/xhtml+xml"
      ],
      "Accept-Language": [
        "en-GB,en;q=0.8,de-DE;q=0.5,de;q=0.3"
      ],
      "Dnt": [
        "1"
      ],
      "Accept-Encoding": [
        "gzip, deflate, br"
      ],
      "Referer": [
        "https://[redacted]pilot.host/user"
      ],
      "Sec-Fetch-Mode": [
        "cors"
      ]
    },
    "tls": {
      "resumed": false,
      "version": 772,
      "cipher_suite": 4865,
      "proto": "h2",
      "proto_mutual": true,
      "server_name": "[redacted]pilot.host"
    }
  },
  "common_log": "[redacted ip] - - [06/Feb/2022:02:55:54 +0000] \"GET /sign_out HTTP/2.0\" 404 1722",
  "user_id": "",
  "duration": 0.008567908,
  "size": 1722,
  "status": 404,
  "resp_headers": {
    "X-Runtime": [
      "0.005184"
    ],
    "Content-Length": [
      "1722"
    ],
    "Server": [
      "Caddy"
    ],
    "Content-Type": [
      "text/html; charset=UTF-8"
    ],
    "X-Request-Id": [
      "da43674e-ffb3-4de2-95ed-1b8a6b9a1513"
    ]
  }
}
```

Can someone confirm this behaviour for the main branch as of today?

**Comment by rriemann** [comment]
So I have done some research on this issue.

My browser is sending a GET request to destroy the session. However, the devise route expects DELETE:

https://github.com/renatolond/mastodon-twitter-poster/blob/b09bec72ae67a4b6c2c30e3fec08d04356831529/config/routes.rb#L15-L17

So a possible solution could be

1. make devise accept GET: https://github.com/heartcombo/devise/issues/4570#issuecomment-673501365
2. make the web interface send a DELETE request: https://github.com/heartcombo/devise/issues/4570#issuecomment-740812109

**Comment by rriemann** [comment]
Hi @renatolond ,

just noticed that you fixed the problem already in https://github.com/renatolond/mastodon-twitter-poster/commit/e7578b50c2001536a1ba41f2a990cc5ab682d471 . Thank you so much.

When checking the network log, I noticed that after a logout, the user is redirected to `/`, which makes sense. For some strange reason, the browser will do that request also with DELETE, which gives a 404 error. However, 404 seems to be mapped to `/`…

Feel free to close anyway.

![image](https://user-images.githubusercontent.com/111932/152892946-49bfc886-a797-43bd-be92-733e38fc01ea.png)

**Comment by renatolond** [comment]
Yeah, I had noticed that extra `DELETE` too, but I'm not sure if it's fixable, since I imagine it's because of the 302 in the sign out :thinking:
