### ISSUE TITLE
Mastodon instance login fails, not logged on server

### ISSUE THREAD

**Issue by ljwrites** [renatolond/mastodon-twitter-poster#676]
I can't log into the https://crossposter.masto.donte.com.br/ site from a mastodon instance on Debian 10 ( https://writeout.ink/ ), which fails with a "We're sorry, but something went wrong" message. This does not happen with two other Mastodon instances I've tried. On the other hand, accounts on the problematic instance have successfully connected via OAuth to other services (Pinafore, DokuWiki). 

The strange thing about the crossposter error is that efforts to log in from there don't seem to be registering on the instance logs at all. When I run a comparison check by doing an OAuth login to a wiki hosted on the subdomain with the following log command:

`sudo journalctl -r -u mastodon-web.service`

The login was logged this way:

```
Mar 14 14:30:49 ubuntu-4gb-nbg1-2 bundle[32324]: [3317c723-e0d9-4961-bee6-fac5079ed5c8] method=POST path=/oauth/token format=html controller=Oauth::TokensController action=create status=200 duration=24.14 view=1.37 db=5.83
Mar 14 14:30:46 ubuntu-4gb-nbg1-2 bundle[32324]: [0c76c33c-585f-45fa-9b33-ca511ff26dad] method=GET path=/oauth/authorize format=html controller=Oauth::AuthorizationsController action=new status=302 duration=29.14 view=0.00 db=7.44 location=https://wiki.writeout.ink/doku.php
Mar 14 14:30:45 ubuntu-4gb-nbg1-2 bundle[32324]: [8467fd35-1b42-4830-9cf3-67f4df1a5adb] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=302 duration=107.33 view=0.00 db=13.22 location=https://writeout.ink/oauth/authorize

```

Same with Pinafore:

```
Mar 14 14:41:30 ubuntu-4gb-nbg1-2 bundle[32324]: [a2778c6d-4d1f-4738-ab52-9f057d52618c] method=POST path=/oauth/token format=json controller=Oauth::TokensController action=create status=200 duration=29.68 view=1.21 db=5.88
Mar 14 14:41:29 ubuntu-4gb-nbg1-2 bundle[32324]: [d2d41900-5723-4721-bffc-db858ecb449f] method=POST path=/oauth/authorize format=html controller=Oauth::AuthorizationsController action=create status=302 duration=34.38 view=0.00 db=11.06 location=https://pinafore.social/settings/instances/add
Mar 14 14:41:26 ubuntu-4gb-nbg1-2 bundle[32324]: [541835cb-5eb2-458d-ac60-80f5a9e5c2ce] method=GET path=/oauth/authorize format=html controller=Oauth::AuthorizationsController action=new status=200 duration=38.13 view=17.68 db=5.51
Mar 14 14:41:25 ubuntu-4gb-nbg1-2 bundle[32324]: [724aac57-85b5-47a4-8c6f-049080438eb9] method=POST path=/auth/sign_in format=html controller=Auth::SessionsController action=create status=302 duration=105.85 view=0.00 db=10.74 location=https://writeout.ink/oauth/authorize
```

Similar messages do not appear during the time I tried to log in through the crossposter site, however. The writeout instance is not on the instance blocklist, and in case it's relevant masto.donte.com.br appears as a federated instance without any restrictions. Is there a reason login attempts from the crossposter would be completely cut off and not even logged?

**Comment by renatolond** [comment]
So, the way ruby works is that if there's an IPv6 registered it will use that (and it does not fallback to the ipv6), since that instance has IPv6 and does not answer on it, the crossposter fails to login: https://ipv6-test.com/validate.php?url=writeout.ink
The solution is to either remove the AAAA record or to fix it :)

**Comment by ljwrites** [comment]
Thank you so much! I never would have figured this out on my own. I'll research and work with my provider to fix the record.
