### ISSUE TITLE
Issues with crossposter language variables being blank

### ISSUE THREAD

**Issue by Doridian** [renatolond/mastodon-twitter-poster#701]
I have just spent a while setting up a crossposter instance and trying to debug it.
I am using Docker (with the provided docker-compose file).
The instance seems working fine, but every single language variable (`I18n.t` function) comes up as blank, so it is almost unusable except if you already know what the buttons do.
I added debug logs where ever I could think to add them and it seems the locale is detected right (English), the locale file is in the container, but it just results in a blank return somehow.

I have attached a picture of how my instance looks right now.
![firefox_stSxKfcpnE](https://user-images.githubusercontent.com/631409/165190945-a00a7555-5f3d-4182-a048-5d43be90113a.png)

I am unsure if this is something I did wrong, or a bug in the code.

**Comment by renatolond** [comment]
Hey :)
It should be fixed now, when someone adds a language from weblate sometimes it messes up the language code and takes over english. Try pulling it now and trying again to see if it fixes it for you :)

**Comment by Doridian** [comment]
@renatolond Thanks for the quick fix. That did the trick  :)
