### ISSUE TITLE
Mamot.fr instance is blocked 

### ISSUE THREAD

**Issue by mapperfr** [renatolond/mastodon-twitter-poster#704]
Hi, 
Trying to connect my Mastodon account @mapper@mamot.fr to the crossposter but it doesn't work. Error message says "Sorry, mamot.fr is blocked in this instance." I remember having the same issue a while ago with the same account.
Is it a bug? Mamot.fr is an instance administrated by La Quadrature du Cercle, a respected and respectable French organisation devoted to the protection of digital rights. 38K users are registered on this instance. It would be great to be able to use mastodon-twitter-poster.
Best regards,
Jeremy

**Comment by renatolond** [comment]
Hi, Jeremy!
The crossposter.masto.donte.com.br is an instance of the crossposter that I run and follows the blocklist from masto.donte.com.br, which I also run. We had several issues with moderation from mamot.fr in the past.
There's other instances of the crossposter and other crossposters out there. Mamot.fr could also run their own instance of the crossposter if they want to.
Best,
Renato
