### ISSUE TITLE
shorten @username@twitter.com to @username

### ISSUE THREAD

**Issue by nrchtct** [renatolond/mastodon-twitter-poster#71]
When tooting from Mastodon, it would be very handy if the @user@instance convention for Twitter users would be shortened so that @username appears on Twitter as a linked text.

**Comment by renatolond** [comment]
Hi!

if I understood correctly, what you mean is this: https://mastodon.xyz/@renatolonddev/7141990 -> https://twitter.com/renatolonddev/status/898100581549658112 ?

**Comment by nrchtct** [comment]
hi Renato, sorry for late reply on this: Yes, and it seems to work already… i believe it did not work before when i tried it, but maybe i did something wrong. Consider the case closed. Thank you!
