### ISSUE TITLE
Support Twitter Circle

### ISSUE THREAD

**Issue by baruchiro** [renatolond/mastodon-twitter-poster#711]
https://help.twitter.com/en/using-twitter/twitter-circle

I think we need to add an option to filter tweets to Circle from being crossposted to Mastodon, because the idea of the circle is to post to specific people, and not for all of them in mastodon.

**Comment by renatolond** [comment]
Hey @baruchiro, I haven't had the time to work on new features of the crossposter lately. I'm open to contributions, but I probably won't have the time to check this myself.
Historically, however, twitter API has been quite behind on new features.

**Comment by timonsku** [comment]
+1 Right now it just posts everything to Mastodon from this feature.

**Comment by renatolond** [comment]
You'd have to add a new config to allow/block circle posts, then somewhere in process_tweet (https://github.com/renatolond/mastodon-twitter-poster/blob/main/lib/twitter_user_processor.rb#L116) decide based on the circle status.
I can't see circles in tweetdeck, so I would assume it's not available in the API just yet

**Comment by andypiper** [comment]
Current status on the Twitter side:

- Twitter API v1.1 is not being enhanced actively, Twitter Circle support is not available
- Twitter API v2 correctly does not have Circle posts on a user Tweet Timeline, but at the moment does not provide access to Circle Tweets at all (being worked on)

If the app used Twitter API v2 then the Circle posts would not be visible.
