### ISSUE TITLE
Content warning as link when posting from Mastodon to Twitter

### ISSUE THREAD

**Issue by Eoin-ONeill-Yokai** [renatolond/mastodon-twitter-poster#712]
It would be nice to have the option to post the content warning posts as a link to the mastodon posting itself so that the behavior can be somewhat simulated on twitter. This would basically post a message like...

```
[CW Header][Link to CW Post on the Mastodon Instance]
```

Thanks!

**Comment by renatolond** [comment]
That's as far as I remember, already the behavior: https://twitter.com/renatolonddev/status/968823166201188353 / https://mastodon.xyz/@renatolonddev/99602923360984263
Did you test and get something different?

**Comment by Eoin-ONeill-Yokai** [comment]
Ah I guess I misunderstood the description then. I've tested it an it seems to work.
