### ISSUE TITLE
[Feature Request]: Allow Delay

### ISSUE THREAD

**Issue by Guacam-Ole** [renatolond/mastodon-twitter-poster#724]
Because there is quite a bunch of people that are the same on Mastodon as on Twitter I would prefer to engage those people mainly on my "main" Network, because usually (and understandibly) they only reply on one of those networks. 

So it would for example be great if I could enter a delay that all posts I wrote on Mastodon will be delayed for xxx minutes before being posted on Twitter (and vica-versa)

**Comment by renatolond** [comment]
Hi @OleAlbers, I haven't had the time to work on new features of the crossposter lately. I'm open to contributions, but I probably won't have the time to check this myself.
