### ISSUE TITLE
I have this error after reinstalling my mastodon instance

### ISSUE THREAD

**Issue by raymand211092** [renatolond/mastodon-twitter-poster#767]
The first time I mounted my mastodon instance it worked fine for me..but after I reinstall it is giving me this error
"The client authentication failed either because it is an unknown client or the client authentication is not included or the authentication method is not confirmed."
My instance its https://maston.grupotd.nat.cu

**Comment by renatolond** [comment]
Hi!
Since the fediverse doesn't handle well in general re-installed instances, the crossposter doesn't treat it specially either. I manually removed the old server credentials and you should be able to login again now.

**Comment by raymand211092** [comment]
Thank you very much

**Comment by raymand211092** [comment]
Due to problems in my vps short space limitations of my operator...I had to reinstall my instance again...and it gives me the error described above again, if it's not too much trouble I could delete the old credentials.

I am very sorry for the inconvenience, i promise not to repeat it again.

My instance its https://maston.grupotd.nat.cu/

**Comment by renatolond** [comment]
Hey, @raymand211092, https://crossposter.masto.donte.com.br/ is shutting down, so I'm not accepting new sign-ups anymore. Even if I remove your old credentials, you won't be able to sign-up with new ones. See https://write.as/renatolond/timeline-for-the-shutdown-of-the-mastodon-twitter-crossposter-instance-at for more information and possible options.
