### ISSUE TITLE
Mysterious loss of URL (twitter --> mastodon, involving quote-tweet)

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#81]
The moo.com part got removed, including the space before it! [Tweet](https://twitter.com/cassolotl/status/977824584488620033), [toot](https://dev.glitch.social/@cassolotl/99743614009958559).

![screen shot 2018-03-25 at 09 33 13](https://user-images.githubusercontent.com/6607512/37873227-cbbec4dc-300f-11e8-8fb8-a70832d97c41.png)
![screen shot 2018-03-25 at 09 33 26](https://user-images.githubusercontent.com/6607512/37873228-cdfbe540-300f-11e8-8e96-13b9f6f0d046.png)

**Comment by renatolond** [comment]
Mysterious indeed, I can't seem to reproduce it on my tests. I'll take a deep look on it and let you know :)

**Comment by Cassolotl** [comment]
Thanks! :)

**Comment by renatolond** [comment]
It took me a while, @Cassolotl, but I finally fixed this one, thanks for reporting! :D

**Comment by Cassolotl** [comment]
Aww nice one, thank you! :)
