### ISSUE TITLE
Privacy issue: Tweets in Twitter Circle still get crossposted to Mastodon with same privacy settings as normal tweets

### ISSUE THREAD

**Issue by Kiloku** [renatolond/mastodon-twitter-poster#828]
When I tweet within my Twitter Circle (the new-ish feature similar to Close Friends on instagram), those tweets become public toots on Mastodon just like my public tweets. 
This is dangerous for the user's privacy

**Comment by renatolond** [comment]
Hey, this is a duplicate of #711, you can follow the conversation over there :)
