### ISSUE TITLE
Add "CN" and "Spoiler" to the list of things that will cause a content warning

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#83]
So we've got CW for content warning and TW for trigger warning. I'm wondering if you'd be up for adding CN, which stands for content note, and Spoiler?

Because sometimes you want to do a content warning on Mastodon, but something as extreme was "warning" feels a bit weird to post in a tweet!

**Comment by renatolond** [comment]
Of course :)

What would be the format?

`Spoiler: Black Panther`
And
`CN: Black Panther`
?

**Comment by Cassolotl** [comment]
Yes, that looks great! :)

**Comment by Cassolotl** [comment]
Woo thank you! :)
