### ISSUE TITLE
Auto-detect twitter-mentions in Mastodon post

### ISSUE THREAD

**Issue by baeuchle** [renatolond/mastodon-twitter-poster#854]
When cross-posting from Mastodon to Twitter, mentions like @baeuchle@twitter.com should be translated to @baeuchle; instead, I get &lt;elephant&gt;baeuchle@twitter.com.

Popular twitter-mirror-only sites (like birdsite.live) might be included.

This is related to #160, but highlights the one instance where there can actually be a general rule how to handle it.

**Comment by renatolond** [comment]
I'm not sure I understand your point, when you say be translated to `@baeuchle`, what do you expect of this mention, that it mentions a user in Mastodon or that it links back to twitter?

**Comment by baeuchle** [comment]
The tweet should mention the twitter user.

(oh sorry I just realised I used &lt;&gt; which was cobbled up. I amended the message, see the elephant in the room :+1: )

My rational for this: I use the crossposter from Mastodon to Twitter only (not backwards), writing my 'original content' on Mastodon. Sometimes I'm torn between doing this and going on Twitter, because I want to mention someone there. I'd like to be able to toot something that translates directly into a mention in the cross-posted tweet. Writing '@someuser@twitter.com' seems to be the most straight-forward way of doing this, and I cannot imaging any other (sensible) thing that anyone would use that string for, thus it shouldn't break anything for anyone. (And now that I put 'sensible' there, I should say: nothing that doesn't deserve to be broken :) )

**Comment by renatolond** [comment]
Ah, I understand it now, this is sort-of a duplicate of #131 .
Twitter does not allow for automated tools, such as the crossposter, to mention twitter users without opt-in. The crossposter used to do what you said, but it was flagged as SPAM and I had to open a dispute with twitter and reverse the change.
Even though it comes from a user, since the tool itself does not get triggered by a user action (it is not a client), it cannot post mentions.

**Comment by baeuchle** [comment]
Ah, how unfortunate. Mmh this has ramifications for my own bot (https://github.com/baeuchle/ds100bot), but only slight.

Thanks anyway for the bot and your explanation.
