### ISSUE TITLE
[Feature request] Link multiple Twitter accounts to one Mastodon account

### ISSUE THREAD

**Issue by Cassolotl** [renatolond/mastodon-twitter-poster#859]
I've got a public Twitter account and a private Twitter account.

What I'd really love to do is make it so that the public Twitter crossposts to the Mastodon account as a public Mastodon post, and the private Twitter crossposts to the *same* Mastodon account as a *followers-only* Mastodon post.

So, two Twitter accounts, each with a different Mastodon-side visibility setting, connecting to the same Mastodon account.

I hope that makes sense! :)

Also thanks for all your hard work Lond, I bet you've got a lot going on thanks to the big Twitter Migration thing, so no hurry!

**Comment by rriemann** [comment]
Work on crossposter and this feature could possibly be funded by the EU via https://nlnet.nl/entrust/ (fast procedure).
