### ISSUE TITLE
Precompile the current version ends in an error

### ISSUE THREAD

**Issue by jacotec** [renatolond/mastodon-twitter-poster#860]
Just wanting to update to the current version, but the precompile always ends in:

```
crossposter@mastodonbridge:~/live$ RAILS_ENV=production bundle exec rake assets:precompile
rake aborted!
LoadError: libjemalloc.so.1: cannot open shared object file: No such file or directory - /home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/msgpack-1.5.4/lib/msgpack/msgpack.so
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `require'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/msgpack-1.5.4/lib/msgpack.rb:7:in `<top (required)>'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `require'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `block in <top (required)>'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/explicit_require.rb:45:in `rescue in with_gems'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/explicit_require.rb:41:in `with_gems'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/store.rb:5:in `<top (required)>'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `require_relative'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache.rb:68:in `<top (required)>'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `require_relative'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap.rb:5:in `<top (required)>'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/setup.rb:3:in `require_relative'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bootsnap-1.13.0/lib/bootsnap/setup.rb:3:in `<top (required)>'
/home/crossposter/live/config/boot.rb:4:in `require'
/home/crossposter/live/config/boot.rb:4:in `<top (required)>'
/home/crossposter/live/config/application.rb:1:in `require_relative'
/home/crossposter/live/config/application.rb:1:in `<top (required)>'
/home/crossposter/live/Rakefile:4:in `require_relative'
/home/crossposter/live/Rakefile:4:in `<top (required)>'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/rake-13.0.6/exe/rake:27:in `<top (required)>'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `load'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:58:in `kernel_load'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli/exec.rb:23:in `run'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli.rb:484:in `exec'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli.rb:31:in `dispatch'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/cli.rb:25:in `start'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/exe/bundle:48:in `block in <top (required)>'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/home/crossposter/live/vendor/bundle/ruby/3.1.0/gems/bundler-2.3.3/exe/bundle:36:in `<top (required)>'
/home/crossposter/.rbenv/versions/3.1.0/bin/bundle:25:in `load'
/home/crossposter/.rbenv/versions/3.1.0/bin/bundle:25:in `<main>'
```

Any ideas?

**Comment by renatolond** [comment]
Hmm, can you try `bundle pristine` and then try that again? It seems like one of the dependencies might be out-of-date

**Comment by jacotec** [comment]
@renatolond Thanks, that basically solved the mentioned compile error, although the pristine gave two error messages:

```
Failed to pristine racc (1.6.0). Cached gem /home/crossposter/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/cache/racc-1.6.0.gem does not exist.
Failed to pristine ruby2_keywords (0.0.5). Cached gem /home/crossposter/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/cache/ruby2_keywords-0.0.5.gem does not exist.
```

However, next problem: The page looks really broken now:

![image](https://user-images.githubusercontent.com/3321655/200326605-e1f7110a-d80b-4d63-98d4-08d2a5a99ccb.png)

Any additional post-upgrade steps I might have overseen?

**Comment by renatolond** [comment]
Hmm, can you try following this? https://github.com/renatolond/mastodon-twitter-poster/blob/main/CHANGELOG.md?plain=1#L21

**Comment by jacotec** [comment]
I did all these commands plus a "rails db:migrate".

Looks like some things are missing ...

![image](https://user-images.githubusercontent.com/3321655/200332482-913c74bb-0c8e-4632-8e14-4c77a96b1fee.png)

**Comment by renatolond** [comment]
In that case, can you try doing:
`rails assets:clobber` followed by `rails assets:precompile` ?

If that still doesn't work, how are you exposing the service, through nginx?

**Comment by jacotec** [comment]
That does not help.

The service is exposted behind by HAProxy. Nothing changed here, it worked well before the update. But even when I call http://ip:3000 I see the same issue.

**Comment by renatolond** [comment]
if you check `public/assets` on your crossposter folder, do you have those assets? `application-a02eecc2bc7d85b4e7a6637c6ee2e4c9e2fe03539f08a394d583a7e104b868f8.css`

**Comment by jacotec** [comment]
Yes, they are both in this folder.
Sorry for the delay ... I trashed all the rbenv and live directory and started from scratch ... it stays the same after a complete new installation.

**Comment by renatolond** [comment]
Yeah, I think it's something with your HAProxy setup. Nginx would be the one serving those assets in the regular setup, I don't know HAProxy, so I can't help you with the setup, but you can check the nginx config file here: https://github.com/renatolond/mastodon-twitter-poster/blob/main/util/nginx.conf

I don't know how it worked before, though, it was not intentional :thinking:

**Comment by jacotec** [comment]
Put the HAProxy apart ... when I access directly the IP of my VM with http://10.0.1.39:3000 it looks the same.
Or is NGINX mandatory with newer versions?

I'll try NGINX in front meanwhile ...

**Comment by jacotec** [comment]
OK, with NGINX in front of all it now works. I saw in the NGINX config that the /public files are served by NGINX now ... I guess that was changed at some point as with my old version everything came through port 3000.

Thanks for your patience! :-)

**Comment by renatolond** [comment]
Hm, I don't remember if/when this changed, I think I used nginx since the beginning in my setup, so it could've been during an update of a dependency, glad to know it's fixed for you, though! :raised_hands:
