### ISSUE TITLE
Better error message for mistyped accounts?

### ISSUE THREAD

**Issue by edent** [renatolond/mastodon-twitter-poster#861]
If a user makes a typo when entering their Mastodon details and gives a server which doesn't exist, they get this error:

![We're sorry but something went wrong (500)](https://user-images.githubusercontent.com/837136/200156611-b9ff294f-2a28-4e79-a86c-ac0d09a88c89.png)

You can see this if you type in `test@example.com`

**Comment by TonyHoyle** [comment]
This is more than a UI thing.. I think I'm misunderstanding what is meant by 'full mastadon username' in the prompt (I'm just using my mastadon username, but I think it wants something else??) as I just get this error every time I try to connect, so exactly *what* the error is would be very useful.

**Comment by renatolond** [comment]
This should be fixed with https://github.com/renatolond/mastodon-twitter-poster/commit/aace84ff472a21c82dd3fb66a33d5ffaed624ef8 :)
