### ISSUE TITLE
Failing to toot to Twitter

### ISSUE THREAD

**Issue by nikjft** [renatolond/mastodon-twitter-poster#862]
I have Twitter -> Mastodon working, but Mastodon-> Twitter doesn't seem to work. Everything is configured. @inik on Twitter, @inik@twit.social on Mastodon. Using hosted service.

**Comment by renatolond** [comment]
hey, as mentioned over [here](https://masto.donte.com.br/@crossposter/109285812093058222), I'm currently waiting for twitter for a response, the crossposter is currently being rate-limited. For now, if you're unlucky it could take a few hours to crosspost to twitter.
