### ISSUE TITLE
[Feature Request] Crosspost Twitter retweets as Mastodon Boosts if the Tweet also exists on Mastodon

### ISSUE THREAD

**Issue by togamid** [renatolond/mastodon-twitter-poster#863]
In the last few days, I have seen multiple instances where a retweet was posted to Mastodon as a standalone toot, when the retweeted Tweet had also been crossposted to Mastodon already. This leads to unnecessary ugly toots and links to Twitter.
Example: 
Original twitter tweet: https://twitter.com/polenz_r/status/1589259329823444993
Crosspost on mastodon: https://social.dev-wiki.de/@polenz_r/109297267037608946
Crossposted retweet on mastodon: https://sueden.social/@stefanwagner/109298537245619665

If this crossposter automatically checked the profile of the retweeted Twitter Account for a mentioned mastodon account (like for example https://pruvisto.org/debirdify/ ) and then checked the corresponding Mastodon profile if the tweet already exists, such cases could be prevented.
This would of course greatly increase the complexity and effort of processing a retweet, but would be greatly beneficial to the health and growth of Mastodon as a platform by increasing interactions with toots and reducing the number of toots each instance has to save and process.

Edit: This has of course the same issues with identifying the corresponding mastodon account as discussed in https://github.com/renatolond/mastodon-twitter-poster/issues/160

**Comment by ctr49** [comment]
This would require to uniquely identify the original tweet, not only the author's profile. I haven't looked in detail, but have not found an indication that some sort of unique id of the tweet is carried over to Mastodon or if that was even possible.

**Comment by renatolond** [comment]
Hey, I haven't had the time to work on new features of the crossposter lately. I'm open to contributions, but I probably won't have the time to check this myself.
