### ISSUE TITLE
Uncheckable "Don't post mentions from Mastodon to Twitter" option?

### ISSUE THREAD

**Issue by RouxRC** [renatolond/mastodon-twitter-poster#865]
In the Mastodon to Twitter options menu, the third choice is not actually a choice and can therefore not be configured:
![image](https://user-images.githubusercontent.com/1153255/200708208-97f78d52-9405-4d93-abf9-3fa1f1f96e23.png)

**Comment by renatolond** [comment]
That's correct, it's there as a warning, and there's a few other issues about mentions that might change that behaviour such as #155
