### ISSUE TITLE
Boost crossport to Twitter broken?

### ISSUE THREAD

**Issue by RouxRC** [renatolond/mastodon-twitter-poster#866]
Although I checked the "Publish boosts on Twitter as links", it does not seem like any "RT" like I do from Mastodon arrives on Twitter, only direct toots seem to be crossposted.
(I'm using piaille.fr and the french interface on Mastodon Twitter Crossposter, so the exact saying of the option is " Publier les boosts sur Twitter comme des liens (Boosté : https://mastodon.social/@renatolond/15082784) ")

**Comment by renatolond** [comment]
In the https://crossposter.masto.donte.com.br/ I disabled it, because it was being detected as SPAM by twitter. I have to remove that option from the interface as an admin option. I'll see if I can work on it in the next few days.

But to answer your question: yes, boosts are not crossposted but is not a bug :)

**Comment by shogunbr** [comment]
@renatolond  I'm hosting a crossposter instance myself for my personal use and I still can't get boost to twitter working. Is there any variable I need to change as admin?
I've setup the instance last week, so i'm using 4th november 2022 code.

**Comment by renatolond** [comment]
Hey @shogunbr , I haven't tested this piece of code in a while, because this is disabled for a long time for the instance I run, but as far as I know nothing changed and it should work. Do you get any errors?

**Comment by coro1404** [comment]
same issue here

**Comment by jacotec** [comment]
@renatolond Wow, I'm hunting this issue for a good hour, wanted to file an issue and found this.
I'm selfhosting your famous bridge.

The usecase:
In the Mastodon instance of my sports club I have some "groups". One is the main "news feed" of the club. Using tootgroup (https://github.com/oe4dns/tootgroup.py) some users can have their toots automatically boosted by the news feed page. Which works perfectly.

But every new news toot (which are all boosts from the view of the news account) should go to the Twitter account. As the others here report, all is perfectly set up ... but not working.

I really don't want to copy and paste every toot manually to the Birdsite account ... any chance to review your code regarding this bug? Or disclose the needed config option if any?

It would really help us!

**Comment by renatolond** [comment]
@jacotec Do the boosts get ignored? As in, do regular toots get posted after a boost?

**Comment by jacotec** [comment]
@renatolond Yap, I did a short test-toot and it worked immediately. Only the boost was ignored.

**Comment by coro1404** [comment]
@renatolond is it possible to modify crossposter so that crossposting boosts is possible for self-hosted instances?

**Comment by renatolond** [comment]
@coro1404 there's current no limitation on the code for that, the change is only on the instance running in https://crossposter.masto.donte.com.br/, so this behavior is a bug

**Comment by jacotec** [comment]
@renatolond Can we hope for a fix of the bug although you're not using this function by yourself? ;-)

**Comment by renatolond** [comment]
I don't think I'll have the time to check this anytime soon, but I'm open for PRs
