### ISSUE TITLE
Option to add a prefix/suffix when crossposting

### ISSUE THREAD

**Issue by CelsiusVi** [renatolond/mastodon-twitter-poster#868]
Hi!

I'm sorry if this is somehow a repeat of another issue, but searching didn't show any relevant results.

My issue is that me and my circle use Twitter, but we were few in Mastodon, and now that more of them are coming to check it out, it gets rightfully annoying to see double-posts from people you follow in both places, so we were looking for a way to silence/filter the crossposts in Mastodon, and the easiest way would be to have a word or a small indicator that the tweet has been crossed , either as a prefix or a suffix.

At the moment, the only option to alter what gets posted from Twitter to Mastodon is to add a CW, which kinda defeats the purpose of crossposting for the rest of Mastodon users, since it hides the content, and it still shows up in your friends' TL. Thus, I was thinking that the option to add a prefix or suffix such as "TWxpost" or something to that end would be useful.

Thanks for your work and time.

**Comment by valerio-bozzolan** [comment]
I like this issue. I would like to set "Posted from Mastodon" as footer.

This is related:

https://github.com/renatolond/mastodon-twitter-poster/issues/164

**Comment by valerio-bozzolan** [comment]
Hi @renatolond what do you think about?

(P.S. can I donate to you somehow? 🚀)

**Comment by renatolond** [comment]
Hey @valerio-bozzolan and @CelsiusVi, I haven't had the time to work on new features of the crossposter lately. I'm open to contributions, but I probably won't have the time to check this myself.
