### ISSUE TITLE
Unable to connect to mastodon.lol

### ISSUE THREAD

**Issue by hellsworth** [renatolond/mastodon-twitter-poster#879]
Hi there, I'm new to mastodon and looking to setup crossposting with my new mastodon account on mastodon.lol. I'm able to connect the crossposter to my twitter account without any problem but when I try to connect to mastodon.lol I see the following error:

![image](https://user-images.githubusercontent.com/12970280/202771072-b9bcdc0a-bd69-4b80-8074-c29325ebcff8.png)

I've tried both with @hellsworth@mastodon.lol and hellsworth@mastodon.lol since it seems that @username@mastodon.server is more commonly used than username@mastodon.server. Both gave me the same error.

**Comment by renatolond** [comment]
Hey :)
When does the error happen, did it go past the point of asking for your credentials?

**Comment by hellsworth** [comment]
welp it works today, so not sure what was wrong but it seems to have resolved itself :woman_shrugging:
