### ISSUE TITLE
Last image missing on Mastodon

### ISSUE THREAD

**Issue by richlv** [renatolond/mastodon-twitter-poster#880]
Crossposting from Twitter to Mastodon drops the last image. Here are two examples.
Notice how the first Twitter post has 4 images, turned 3 on Mastodon.
The second has two images on Twitter, turned 1 on Mastodon.

https://twitter.com/RihardsOlups/status/1593965462206963712
https://mastodon.social/@richlv/109370805077355276

https://twitter.com/RihardsOlups/status/1593966591582027776
https://mastodon.social/@richlv/109370842358355873

**Comment by silverhook** [comment]
…and if it’s just one image, that one gets dropped just as well.

https://twitter.com/ArmsBerti/status/1594087411734437888
https://mastodon.social/@hook/109372725916219215

**Comment by silverhook** [comment]
I since moved from mastodon.social to a different node and also stopped using twitter completely, so I can’t test this any more, sorry.

**Comment by richlv** [comment]
Haven't posted that many messages with images, but don't recall it happening from the web UI.
Don't recall posting anything with images from any mobile apps.

**Comment by richlv** [comment]
It indeed seems like it could be a problem with that particular instance - I've had twice image missing when posting on it manually via the web interface (once the only image, once the second image out of two).

**Comment by richlv** [comment]
Or maybe not. Haven't seen further images missing after the two or three initial cases of manual posting.
Crosspoting Twitter->Mastodon in this thread, the first post had both images, all the subsequent ones lost all _all_ their images (including one losing 3 images) - except the last post, which was added at a later time.

https://twitter.com/RihardsOlups/status/1598741659772227599
https://mastodon.social/@richlv/109445448398288787

**Comment by richlv** [comment]
Getting most images missing on the M side - another example:

https://twitter.com/RihardsOlups/status/1599119183060430849
https://mastodon.social/@richlv/109451247546723235

**Comment by renatolond** [comment]
> It indeed seems like it could be a problem with that particular instance - I've had twice image missing when posting on it manually via the web interface (once the only image, once the second image out of two).

@richlv  Specially considering this comment, I think you need to contact your admin, because if your instance is ignoring images with regular clients, there's nothing I can do in the crossposter side.

**Comment by richlv** [comment]
I'm wondering if something else might be going on, like me clicking "publish" while the image was still uploading, when I had manual failures.
I haven't seen a manual failure since then, but the crossposter drops images on > 80% of posts. This happens not just for one image per post, in one example three images in a post were missing...

**Comment by richlv** [comment]
After a longer break, had this happen again when directly posting on mastodon.social.
Lately it's not just the last image, also 2 or 3 images are all gone.
Looks like it's indeed just something that crossposter managed to hit in a somewhat more visible way.
