### ISSUE TITLE
@fosstodon.org instance not supported

### ISSUE THREAD

**Issue by JordiBolibar** [renatolond/mastodon-twitter-poster#883]
I've been trying to use the crossposter with my account hosted @fosstodon.org. I get the following error:
```
Sorry, fosstodon.org is blocked in this instance. 
```
Is there a reason why that instance is blocked? Looks like a rather mainstream and harmless server to me.

Thanks in advance!

**Comment by renatolond** [comment]
Duplicate of #853, closing
