### ISSUE TITLE
Add a link to revoke permissions

### ISSUE THREAD

**Issue by ethrgeist** [renatolond/mastodon-twitter-poster#888]
The accounts page should have links to easily revoke permissions, like e.g. https://fedifinder.glitch.me/

For Twitter: `https://twitter.com/settings/connected_apps`
For Mastodon: `https://example.net/oauth/authorized_applications`

Not all users are savvy enough to find these sub menus or get their meaning.

**Comment by renatolond** [comment]
Done in 6bd7e8c8648037d169fdf82cb2b8615092ea1ba3
