### ISSUE TITLE
Failed Mastodon authentication "The page you are looking for isn't here"

### ISSUE THREAD

**Issue by E-11-V** [renatolond/mastodon-twitter-poster#895]
I have managed to link my Twitter account but when I do the same for mastodon and I authorize the link 
![image](https://user-images.githubusercontent.com/84926127/204870048-7d7cb404-4565-4635-b274-d14020c62d45.png)
I get the angry elephant
![image](https://user-images.githubusercontent.com/84926127/204870127-3a15c8bc-853e-4562-8438-3c94bff6a05b.png)
Any ideas? Thank you!!

**Comment by drboone** [comment]
Ditto for us.
