### ISSUE TITLE
[New Feature]: Mastodon post confidentiality of replies to own Tweet

### ISSUE THREAD

**Issue by rriemann** [renatolond/mastodon-twitter-poster#897]
Hi!

To keep the public timeline tidy, it can be a good practice to have the start of a thread with confidentiality=public and all follow up own replies with confidentiality=unlisted.

However, crossposter does not give an option yet to change confidentiality of own replies.

Work on crossposter and this feature could possibly be funded by the EU via https://nlnet.nl/entrust/ (fast procedure).

**Comment by Thzx** [comment]
That would be a great feature. I just saw a 17-tweet thread over several pages of timeline…
