### ISSUE TITLE
[Idea] Allow providing own twitter and/or Mastodon app to use for cross-posting

### ISSUE THREAD

**Issue by Andre601** [renatolond/mastodon-twitter-poster#906]
Given that [the request for elevated API request limits has been denied](https://masto.donte.com.br/@crossposter/109394311694817230), I had the time to quickly think about a possible idea her.

### Idea
Allow people to provide their own App cridentials to use for the crossposting from/to twitter and Mastodon. If I understood it correctly are requests per application (on Twitter), so having a separate application could reduce the calls on the main one and allow the user a faster posting.

So basically, when user provides the accounts to link would there be an option to also provide apps. When set will the crossposter use those for the user instead of the default one, therefore having a separate rate limit bucket.

### Possible Issues
One issue could be logging in I suppose? I assume the application requires you to "log in" using some token or cridentials to then interact with twitter, so in the end could there be a risk of sensitive data being leaked (Tho, you already store oauth approvals/tokens/... to post in the user's name, so....)

### Why not self-host?
Obviously a good idea, but at the same time not 100% feasable for everyone. People like me may not have the spare money to even afford a small server/site/... to run this software on, even if it would be small in RAM, storage and bandwidth.

### Disclaimer
This stuff was writter without having any in-depth knowledge about Mastodon's or Twitter's API, so forgive me if any information is wrong, outdated or alike.

### Extra info
I [originally asked this on Mastodon](https://blobfox.coffee/@andre_601/109483497664691342) towards the crossposter account but thought it might be a good idea to make this issue to have a more open discussion where other people could provide their own input on this entire thing.

**Comment by renatolond** [comment]
I don't think this is a good way to circumvent the limits because it would mean twitter could detect several app accesses from the same IP and then ban the IP altogether (making the situation worse) if they consider that this is some kind of bad faith attempt at going above the limits.
