### ISSUE TITLE
How do I make myself admin?

### ISSUE THREAD

**Issue by VanillaChief** [renatolond/mastodon-twitter-poster#911]
Firstly, I wanted to say that your documentation is really well written. It is a complex system with a lot of moving parts, like you wrote, but it was really easy to set this up with Docker on my NAS with your guide. 
The only thing I don't understand is how to make myself admin. It states to run this command:

`FEDIVERSE_USERNAME=your_user@your.domain.com RAILS_ENV=production bundle exec rake crossposter:make_admin`

but something is missing because I can't just copy and paste it (with my username entered, of course) like the rest of the commands in the Docker guide. Maybe you could make the guide here more detailed?

**Comment by renatolond** [comment]
Hey, I'm not sure since I don't run it in docker myself, but I believe you could run the command by doing something like:

```
docker-compose run --rm web FEDIVERSE_USERNAME=your_user@your.domain.com RAILS_ENV=production bundle exec rake crossposter:make_admin
```

Can you try that and see if it works?

**Comment by rasos** [comment]
This is the way to make a user an admin with Docker:

      docker-compose run -e FEDIVERSE_USERNAME=your_user@your.domain.com --rm web bundle exec rake crossposter:make_admin

You might need to do a `docker stop mastodon-twitter-poster_web_run_1` first if you started it with `-d` as a daemon.

**Comment by amatriain** [comment]
you can also run

```docker exec -it web sh```

to enter the docker container command shell. Once there you can run

```FEDIVERSE_USERNAME=your_user@your.domain.com RAILS_ENV=production bundle exec rake crossposter:make_admin```

and then ```exit``` to get back out of the container command line.
