### ISSUE TITLE
Compulsory marking of toots as coming from a crossposter

### ISSUE THREAD

**Issue by 31SFX4** [renatolond/mastodon-twitter-poster#938]
Toots should be clearly marked as being produced by a crossposter, and the user should not be able to turn this off. There could be either a sentence added at the beginning ("Crossposted from Twitter" or so), or some other way so that fedizens can easily filter crossposts out of their timeline and instance users can block them if they wish.

It's an increasing issue in the Fediverse that too many users just crosspost from Twitter and then do not interact in the Fediverse. Many fedizens want to follow only accounts who actually interact with other fedizens, and having the toots marked clearly would halp to filter this out, or at the very least helps fedizens to see that there's no point interacting with a toot.

**Comment by renatolond** [comment]
Hey, the crossposter is marked by the app: 
![image](https://user-images.githubusercontent.com/173791/215428911-3e6f8a08-db36-407c-92f9-1094ebf99568.png)

At least on Mastodon. This cannot be disabled. There's an open issue open on Mastodon to allow filtering by this field: https://github.com/mastodon/mastodon/issues/8271
