### ISSUE TITLE
shouldn't there be a .env.example file?

### ISSUE THREAD

**Issue by shinenelson** [renatolond/mastodon-twitter-poster#96]
The README mentions `bundle exec foreman start -e .env.production`, but that file doesn't exist.
For obvious reasons, it cannot be checked-into the repository since it should contain credentials.

But shouldn't there at least be a `.env.example` file (and appropriate accompanying documentation) so that a user trying to run this on their own may know what are the required credentials / variables that are required for the application to run properly?

I've been trying to run the application locally, but I haven't been able to get it running and one of the reasons is probably the lack of the `.env` file.

From a quick look, I can figure 4-5 variables that should go in the `.env` file : 
1. `LIBRATO_EMAIL`
2. `LIBRATO_TOKEN`
3. `DYNO`
4. `TWITTER_KEY`
5. `TWITTER_SECRET`

I don't know if the :point_up_2: list is exhaustive or not. Perhaps, there has to be Mastodon credentials somewhere. These are the variables I figured should be required to even get the application going. I was stuck without Twitter credentials. I don't know if there might be other variables that might be required.

It would be highly appreciated if an `.env.example` file could be checked in with appropriate documentation accompanying it.

Aside : is it really important that the `statsd-librato-backend` be checked into the repository? Couldn't the `backends` array be left empty in the repository configuration and then populated during deployment from the `.env` file or something?
This could avoid one additional step in getting the application from running out of the box.

**Comment by renatolond** [comment]
It's a great idea, I will see if I do this ASAP :)

As for the librato backend: the thing is just that I originally tailored this for my own deployment and that is why it is commited. I want to take some time and decouple the statsd from this deploy. It should be configured by itself and restarted/deployed by itself instead. I might do both in the same PR :)
